<a href="https://colab.research.google.com/github/krteja44/Python/blob/master/Copy_of_100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [0]:
print(np.__version__)
print(np.show_config())

1.17.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [0]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [0]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [0]:
?np.add
#%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [0]:
Z = np.zeros(10)
print(Z)
Z[4] = 1
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [0]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [0]:
Z =  np.arange(10,50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [0]:
Z= np.arange(0, 9)
print(Z)
#Z = np.array(Z)
print(Z.reshape(3,3))
print(Z)
Z.resize(3,3)
print(Z)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [0]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [0]:
#np.ones((3,3))
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [0]:
10*np.random.random((3,3,3))

array([[[6.21142511e+00, 3.19349632e+00, 6.16827072e-03],
        [8.61652471e+00, 2.07105150e+00, 4.87319670e-01],
        [3.45952331e+00, 5.38183118e+00, 8.65765434e+00]],

       [[6.99695349e+00, 6.31981595e+00, 1.29447897e+00],
        [3.36061745e+00, 2.22412396e+00, 1.86356050e+00],
        [7.88959318e+00, 1.82910486e+00, 5.72449889e+00]],

       [[8.74339898e+00, 7.97008375e+00, 3.67214347e+00],
        [8.44641838e+00, 4.18529749e-01, 5.80341959e-02],
        [3.43392898e-01, 4.59516973e+00, 1.49617475e+00]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [0]:
Z = np.random.random((10,10))
print(np.min(Z))
print(np.max(Z))
print(Z.min())
print(Z.max())

0.01715355875145841
0.9941671208618541
0.01715355875145841
0.9941671208618541


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [0]:
Z = np.random.random(30)
Z.mean()

0.5660520439297362

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [0]:
Z = np.ones((10,10))
print(Z)
print()
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [0]:
Z = np.ones((5,5))
print(Z)
print()
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0 )
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [0]:
0 * np.nan  ##nan
np.nan == np.nan  ##false
np.inf > np.nan  ##false
np.nan - np.nan   ##nan
np.nan in set([np.nan])  ##true
0.3 == 3*0.1  ##false

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [0]:
np.diag(1+np.arange(4), k=0)
np.diag(1+np.arange(4), k=1)
np.diag(1+np.arange(4), k=-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [0]:
Z = np.zeros((8,8))
print(Z)
Z[1::2,::2]=1
Z[::2,1::2]=1
Z

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [0]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
#Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [139]:
np.random.seed(10)
Z=10*np.random.random((6,7,8))
Z
print(np.unravel_index(99,Z.shape))
#print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [0]:
Z = np.array([[0,1],[1,0]])
Z
np.tile(Z,(4,3))
np.tile(Z,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [0]:
np.random.seed(11)
Z = np.random.random((5,5))
print(Z)
Z = (Z - np.mean(Z))/ (np.std(Z))
print(Z)
print(Z.max())
print(Z.min())


[[0.18026969 0.01947524 0.46321853 0.72493393 0.4202036 ]
 [0.4854271  0.01278081 0.48737161 0.94180665 0.85079509]
 [0.72996447 0.10873607 0.89390417 0.85715425 0.16508662]
 [0.63233401 0.02048361 0.11673727 0.31636731 0.15791231]
 [0.75897959 0.81827536 0.34462449 0.3187988  0.11166123]]
[[-0.83509111 -1.35712193  0.0835228   0.93320082 -0.05612826]
 [ 0.15562453 -1.37885587  0.16193752  1.63729383  1.34181819]
 [ 0.94953283 -1.06733018  1.48177495  1.36246366 -0.88438405]
 [ 0.63256848 -1.35384818 -1.04135371 -0.39324031 -0.90767597]
 [ 1.04373252  1.23624053 -0.30150133 -0.38534632 -1.05783343]]
1.6372938288921894
-1.3788558748998705


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [0]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte,1)])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [0]:
A = np.resize(np.arange(0,14), (5,3))
print(A)
print
B = np.resize(np.arange(0,6), (3,2))
print(B)
print()
print(np.dot(A,B))
print()

#Alternate Sol 
print(A @ B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13  0]]
[[0 1]
 [2 3]
 [4 5]]

[[10 13]
 [28 40]
 [46 67]
 [64 94]
 [26 51]]

[[10 13]
 [28 40]
 [46 67]
 [64 94]
 [26 51]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [0]:
A = np.arange(10)
print(A)
print()
A[(2<A) & (A<9)] *= -1
print(A)


[0 1 2 3 4 5 6 7 8 9]

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


In [0]:
#print(np.arange(11))

[ 0  1  2  3  4  5  6  7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [0]:
import numpy as np
print(np.sum(range(5), -1))  # 0+1+2+3+4
#range(5)
#sum(range(5), -1)
from numpy import *
print(sum(range(5),-1))   ### takes second parameter as axis


10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [0]:
Z = np.array([0]*10)
Z
Z**Z #L
A = np.arange(0,10)
print(A)
print(A >>1)
A <- A  #L
1j*A   #L
A/1/1  #L
#A<A>A  #NL

[0 1 2 3 4 5 6 7 8 9]
[0 0 1 1 2 2 3 3 4 4]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [0]:
np.array(0) / np.array(0)                     ## nan
np.array(0) // np.array(0)                    ## 0
np.array([np.nan]).astype(int).astype(float)  ## [-9.22337204e+18]

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [0]:
A = np.random.uniform(-10,+10,10)
print(A)
print()
np.abs(A)
print()
print(np.ceil(A))
print()
print(np.ceil(np.abs(A)))
print()
print(np.floor(np.abs(A)))  ##round towards zero a floar array
print()
print (np.copysign(np.ceil(np.abs(A)), A))
?copysign

[-5.39901174  7.09073307  2.85198834 -2.25818139 -7.09354801 -8.21080662
  6.61902741 -8.55018532 -8.55361473  8.09344185]


[-5.  8.  3. -2. -7. -8.  7. -8. -8.  9.]

[6. 8. 3. 3. 8. 9. 7. 9. 9. 9.]

[5. 7. 2. 2. 7. 8. 6. 8. 8. 8.]

[-6.  8.  3. -3. -8. -9.  7. -9. -9.  9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [0]:
A = np.arange(10)
B = np.arange(3,6)
print(A)
print(B)
print(np.intersect1d(A,B))

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [0]:
#defaults = np.seterr(all="ignore")
#Z = np.ones(1) / 0
#print(Z)

##Back to defaults
_ = np.seterr(**defaults)
Z = np.ones(1) / 0
Z

array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [0]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [0]:
print(np.datetime64('today')-1,np.datetime64('today'),np.datetime64('today')+1)
print()
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print(np.datetime64('today', 'M') + np.timedelta64(1,'M'))

2020-03-05 2020-03-06 2020-03-07

2020-03-05
2020-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [0]:
print(np.arange('2016-07', '2016-08', dtype= 'datetime64[D]'))
print()
print(np.arange('2016-07', '2016-09', dtype= 'datetime64[M]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']

['2016-07' '2016-08']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [0]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out=B)
np.divide(A,2, out=A)
np.multiply(A,-1, out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

In [0]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [0]:
Z = 10*np.random.random((3,3))
np.random.seed(10)
A = np.random.uniform(-10,+10,10)
print(A)

#print(Z)
print()
print(A - A%1)
print(np.floor(A))
print(np.ceil(A)-1)
#print(np.abs(Z))
print(A.astype(int))   ##correct
print(np.trunc(Z))


[ 5.42641287 -9.58496101  2.6729647   4.97607765 -0.02985975 -5.50406709
 -6.0387427   5.21061424 -6.61778327 -8.23320372]

[  5. -10.   2.   4.  -1.  -6.  -7.   5.  -7.  -9.]
[  5. -10.   2.   4.  -1.  -6.  -7.   5.  -7.  -9.]
[  5. -10.   2.   4.  -1.  -6.  -7.   5.  -7.  -9.]
[ 5 -9  2  4  0 -5 -6  5 -6 -8]
[[6. 9. 0.]
 [5. 8. 6.]
 [7. 2. 9.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [0]:
np.tile(np.arange(0,5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [0]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [0]:
#np.fromiter(np.random.randint(10), dtype='array')
print(np.random.randint(0,10,size=10)) ##doubt

[9 1 9 4 2 6 7 8 8 9]


In [0]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [0]:
np.linspace(0,1,11, endpoint=False)[1:]
np.random.uniform(0,1,10)

array([0.35165264, 0.75464769, 0.29596171, 0.88393648, 0.32551164,
       0.1650159 , 0.39252924, 0.09346037, 0.82110566, 0.15115202])

In [0]:
Z = np.linspace(0,1,11,endpoint=False)
print(Z)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [0]:
np.sort(np.random.uniform(0,1,10))

array([0.25137413, 0.38411445, 0.45630455, 0.53455795, 0.59020136,
       0.59737165, 0.82612284, 0.90283176, 0.94426071, 0.98762547])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [0]:
np.add.reduce(np.arange(10))

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [0]:
A = np.arange(0,3)
B = np.array([0,1,2])
np.array_equal(A,B


True

In [0]:
A = np.array([0,1.12,2.34])
B = np.array([0,1.10,2.00])
equal = np.allclose(A,B, rtol=0.2)
equal2 = np.allclose(A,B)
print(equal, equal2)

True False


#### 43. Make an array immutable (read-only) (★★☆)

In [0]:
A = np.zeros(10)
B = np.zeros(10)
A.flags.writeable = False
B[0]=1
print(B)
A[0] = 1
print(A)


[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [0]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
print(Z)
print()
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print()
print(T)

[[0.30087131 0.02539978]
 [0.30306256 0.24207588]
 [0.55757819 0.56550702]
 [0.47513225 0.29279798]
 [0.06425106 0.97881915]
 [0.33970784 0.49504863]
 [0.97708073 0.44077382]
 [0.31827281 0.51979699]
 [0.57813643 0.85393375]
 [0.06809727 0.46453081]]

[0.30194154 0.38787581 0.79416096 0.5581051  0.98092564 0.60039534
 1.07189939 0.60949691 1.03123449 0.46949559]

[0.08422105 0.67398766 0.79245791 0.55227896 1.50524896 0.96938476
 0.42377912 1.02138021 0.97565526 1.42523941]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [0]:
import numpy as np

A = 10* (np.random.random(10))
print(A)
print(A.max())
print(A.argmax())
max = np.where(A==A.max())
A[max]=0
print(A)



[8.87888546 8.30245279 7.42511536 2.03836863 5.05547432 6.77076919
 8.1103373  3.35047503 2.19503501 1.70357311]
8.878885457365971
0


In [0]:
A = 10* (np.random.random(10))
print(A)
print(A.max())
print(A.argmax())
A[A.argmax()] = 0
print(A)

[8.87779232 0.57629147 0.63473345 2.62216868 4.46069501 4.71836947
 3.25580706 8.29111033 0.39457511 9.04254025]
9.042540245305076
9
[8.87779232 0.57629147 0.63473345 2.62216868 4.46069501 4.71836947
 3.25580706 8.29111033 0.39457511 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [0]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                               np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [0]:
X = np.arange(8)
Y = X+0.5
C = 1.0/ np.subtract.outer(X,Y)
print(np.linalg.det(C))
print(X,Y)

3638.163637117973
[0 1 2 3 4 5 6 7] [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]


In [0]:
X = np.floor(10*(np.arange(8)))
Y = X+0.5
X = X.reshape((-1,1))
diffmatrix = X-Y
cauchym = 1.0/ diffmatrix
print(X , '\n \n', Y, '\n \n',cauchym,'\n \n' )

cauchym2 = np.array([[ 1.0/(x_i-y_j) for y_j in Y] for x_i in X])
cauchym2 = cauchym2.reshape((len(X),len(Y)))
print(cauchym2)


[[ 0.]
 [10.]
 [20.]
 [30.]
 [40.]
 [50.]
 [60.]
 [70.]] 
 
 [ 0.5 10.5 20.5 30.5 40.5 50.5 60.5 70.5] 
 
 [[-2.         -0.0952381  -0.04878049 -0.03278689 -0.02469136 -0.01980198
  -0.01652893 -0.0141844 ]
 [ 0.10526316 -2.         -0.0952381  -0.04878049 -0.03278689 -0.02469136
  -0.01980198 -0.01652893]
 [ 0.05128205  0.10526316 -2.         -0.0952381  -0.04878049 -0.03278689
  -0.02469136 -0.01980198]
 [ 0.03389831  0.05128205  0.10526316 -2.         -0.0952381  -0.04878049
  -0.03278689 -0.02469136]
 [ 0.02531646  0.03389831  0.05128205  0.10526316 -2.         -0.0952381
  -0.04878049 -0.03278689]
 [ 0.02020202  0.02531646  0.03389831  0.05128205  0.10526316 -2.
  -0.0952381  -0.04878049]
 [ 0.01680672  0.02020202  0.02531646  0.03389831  0.05128205  0.10526316
  -2.         -0.0952381 ]
 [ 0.01438849  0.01680672  0.02020202  0.02531646  0.03389831  0.05128205
   0.10526316 -2.        ]] 
 

[[-2.         -0.0952381  -0.04878049 -0.03278689 -0.02469136 -0.01980198
  -0.01652893 -

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [43]:
import numpy as np

for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
print()
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807

-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [54]:
np.set_printoptions(threshold=1000)
Z = np.zeros((100,100))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [60]:
A = np.arange(100)
print(A)
v = np.random.uniform(0,100)
print(v)
i = (np.abs(A-v)).argmin()  #abs because 0-50 is min but not closest to 50
A[i]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
44.254062689228114


44

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [62]:
Z = np.ones(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)   ##doubt

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.6/dist-packages/numpy/core/numeric.py:214: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [70]:
Z = np.random.randint(0,10,6).reshape(3,2)
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)
print(X,Y)
print(X.T)


import scipy
import scipy.spatial
print(scipy.spatial.distance.cdist(Z,Z))

[[1 5]
 [7 8]
 [9 3]]
[[0.         6.70820393 8.24621125]
 [6.70820393 0.         5.38516481]
 [8.24621125 5.38516481 0.        ]]
[[1 7 9]] [[5 8 3]]
[[1]
 [7]
 [9]]
[[0.         6.70820393 8.24621125]
 [6.70820393 0.         5.38516481]
 [8.24621125 5.38516481 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [86]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
print(Z.view(np.int32))
Y = Z.view(np.int32)
Y[:] = Z
print(Y)



[78.627846 72.93771  11.098528 32.591343 20.18468  32.03263  86.96162
 10.682668 33.66301  70.220665]
[1117602165 1116856348 1093768082 1107451273 1101101626 1107304810
 1118694489 1093332021 1107732204 1116500219]
[78 72 11 32 20 32 86 10 33 70]


In [84]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
#Y = Z.view(np.int32)
#print(Y[1])
#Y[:] = Z
#print(Y[1])

Z.astype('int32')

[ 6.609193 28.141796 51.05108  12.110038 44.127316 78.384964 55.245213
 99.129974 50.184258 25.632967]


array([ 6, 28, 51, 12, 44, 78, 55, 99, 50, 25], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [88]:
from io import StringIO

s = StringIO ('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",")
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [95]:
Z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
  print(index,value)

print()
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [101]:
#X, Y = 
#print(np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10)))
print (np.linspace(-1,1,10))

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [102]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [118]:
n = 10
p = 3
Z = np.zeros((n,n))
print(Z)
print()
random = np.random.choice(range(n*n), p, replace=False) 
#given n*n as there are 100 indices for n=10
print(random)
print()
np.put(Z, random,random)
print(Z)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[40 54 80]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [40.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 54.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [80.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [129]:
Z =  np.arange(0,10).reshape(5,2)
print(Z)
rowmean= np.tile(Z.mean(axis=1),(2,1)).T
print(Z- rowmean)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]]


In [136]:
Z =  np.arange(0,10).reshape(5,2)
#Z-Z.mean(axis=1, keepdims=True)
Z-Z.mean(axis=1, keepdims=True)  #keepdims =T returns a 2D array


array([[-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5]])

#### 59. How to sort an array by the nth column? (★★☆)

In [162]:
random
Z = np.random.randint(0,13,(4,3))
print(Z)
#print(np.sort(Z))
#print(Z)

[[ 3  0 12]
 [12 10  1]
 [ 2  7  8]
 [ 8  6  0]]


In [174]:
#print(Z[1].argsort())
#print(Z[2,].argsort())
#print(Z[:,2].argsort())
print(Z[Z[:,2].argsort()])  ## order by column 3 (index 2)
print()
print(Z[:,Z[1].argsort()])   ## order by 2nd row

[[ 8  6  0]
 [12 10  1]
 [ 2  7  8]
 [ 3  0 12]]

[[12  0  3]
 [ 1 10 12]
 [ 8  7  2]
 [ 0  6  8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)