NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

[[ 1., 0., 0.],
 [ 0., 1., 2.]]

In [1]:
import numpy as np
np.random.RandomState(seed=52)
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.itemsize

8

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

Array Creation


In [10]:
import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype,
a.ndim,
a.shape,
type(a),
a.itemsize)

[2 3 4]
int64 1 (3,) <class 'numpy.ndarray'> 8


In [11]:
b = np.array([1.2,4.5,5.1])
b.dtype

dtype('float64')

In [0]:
#a = np.array(1,2,3,4)  #WRONG
a = np.array([1,2,3,4])  #RIGHT

In [13]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)
print(b.dtype,
b.ndim,
b.shape,
type(b),
b.itemsize)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
float64 2 (2, 3) <class 'numpy.ndarray'> 8


In [14]:
c = np.array([ [1,2] , [3,4] ], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones( (2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
np.empty( (2,3) )  #uninitialized, output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
np.arange( 10,30,5 )
np.arange( 10,31,5 ) #check this
np.arange( 0,2,0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [19]:
from numpy import pi
print(np.linspace(0,2,9))  #9 numbers from 0 to 2

x= np.linspace(0,2*pi,100)  #useful to evaluate function at lots of points
f=np.sin(x)
print(f)



[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.1367739

In [0]:
#array, zeros, zeros_like, ones, ones_like, empty, 
#empty_like, arange, linspace, numpy.random.rand, 
#numpy.random.randn, fromfunction, fromfile

Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

the last axis is printed from left to right,
the second-to-last is printed from top to bottom,
the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [21]:
a = np.arange(6)   #1d array
print(a)
print()

b = np.arange(12).reshape(4,3)   #2d array
print(b)
print()

c = np.arange(24).reshape(2,3,4)   #3d array
print(c)

[0 1 2 3 4 5]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [22]:
print(np.arange(10000))
print()
print()
print(np.arange(10000).reshape(100,100))

#To disable this behaviour and force NumPy to print the entire array, 
#you can change the printing options using set_printoptions.

#np.set_printoptions(threshold=np.nan) not supported in python 3



[   0    1    2 ... 9997 9998 9999]


[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [23]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(b)

c = a-b
print(c)

print(b**2)

print(10*np.sin(a))

a<35

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


array([ True,  True, False, False])

In [24]:
A = np.array( [[1,1],
            [0,1]] )

B = np.array( [[2,0],
            [3,4]] )
print(A * B)                       # elementwise product
print()
print(A @ B)                       # matrix product
print()
print(A.dot(B))                    # another matrix product

[[2 0]
 [0 4]]

[[5 4]
 [3 4]]

[[5 4]
 [3 4]]


In [25]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)
print()


b += a
print(b)
print()

#print(a += b)                  # b is not automatically converted to integer type

  

[[3 3 3]
 [3 3 3]]

[[3.60264588 3.63618358 3.22944501]
 [3.17855668 3.71172192 3.16137945]]



In [26]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print(b.dtype.name)
print()
c = a+b
print(c)
print()
print(c.dtype.name)
print()
d = np.exp(c*1j)
print(d)
print()

d.dtype.name

float64

[1.         2.57079633 4.14159265]

float64

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]



'complex128'

In [27]:
a=np.random.random((2,3))  
print(a)
print()
print(a.sum())    ###unary operations
print()
print(a.min())
print()
print(a.max())

[[0.31217298 0.75578244 0.02196715]
 [0.00248591 0.67601426 0.40005798]]

2.168480726804988

0.002485906790943737

0.7557824434288327


In [28]:
import numpy as np

b = np.arange(12).reshape(3,4)
print(b)
print()

print(b.sum(axis=0))     # sum of each column
print()

print(b.min(axis=1))   # min of each row
print()

print(b.cumsum(axis=1))   # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[12 15 18 21]

[0 4 8]

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


## Universal Functions

In [29]:
B = np.arange(3)
print(B)
print()

print(np.exp(B))
print()

print(np.sqrt(B))
print()

C = np.array([2., -1, 4.])
print(C)
print()

print(np.add(B, C))
np.subtract(B,C)


[0 1 2]

[1.         2.71828183 7.3890561 ]

[0.         1.         1.41421356]

[ 2. -1.  4.]

[2. 0. 6.]


array([-2.,  2., -2.])

## Indexing, Slicing and Iterating

In [30]:
a = np.arange(10)**3
print(a)

print(a[2])
print()

print(a[2:5])
print()

print(a[:6:2])
print()

print(a[::-1])
print()

for i in a:
  print(i**(1/3.))


[  0   1   8  27  64 125 216 343 512 729]
8

[ 8 27 64]

[ 0  8 64]

[729 512 343 216 125  64  27   8   1   0]

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [31]:

def f(x,y):
  return 10*x+y


#Each parameter represents the coordinates of the array varying 
#along a specific axis. For example, if shape were (2, 2), 
#then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]])
b = np.fromfunction(f, (5,4), dtype=int)
print(b)
print()

print(b[2,3])
print()

print(b[0:5,1])
print()

print(b[: ,1])
print()

print(b[1:3, :])   ##1:3 gives rows 1 and 2 only

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

23

[ 1 11 21 31 41]

[ 1 11 21 31 41]

[[10 11 12 13]
 [20 21 22 23]]


In [32]:
b[-1] ##similar to b[-1,:]

array([40, 41, 42, 43])

In [33]:
c = np.array( [[[  0,  1,  2],          # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

#c.shape
print(c)
#c.ndim
print()

print(c[1,...])  #sames as c[1,:,:] or c[1]
print()

print(c[...,2])

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]

[[100 101 102]
 [110 112 113]]

[[  2  13]
 [102 113]]


In [34]:
##Iterating over multidimensional arrays

for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [35]:
#flat attribute which is an iterator over all the elements of the array:

for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# **Shape** **Manipulation**

In [36]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print()

print(a.shape)

[[0. 8. 4. 6.]
 [3. 7. 0. 6.]
 [6. 5. 5. 8.]]

(3, 4)


In [37]:
# the following commands return a modified array, 
#but do not change the original awway

print(a.ravel())    ##returns the arrat flattened
print()

print(a.reshape(6,2))
print()

print(a.T)
print(a.T.shape)

[0. 8. 4. 6. 3. 7. 0. 6. 6. 5. 5. 8.]

[[0. 8.]
 [4. 6.]
 [3. 7.]
 [0. 6.]
 [6. 5.]
 [5. 8.]]

[[0. 3. 6.]
 [8. 7. 5.]
 [4. 0. 5.]
 [6. 6. 8.]]
(4, 3)


The order of the elements in the array resulting from ravel() is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the array is treated as “C-style”. NumPy normally creates arrays stored in this order, so ravel() will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions ravel() and reshape() can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest

The **reshape** function returns its argument with a modified shape, whereas the ndarray.**resize** method modifies the array itself

In [38]:
print(a)
print()

print(a.resize((2,6)))
print()

print(a)

[[0. 8. 4. 6.]
 [3. 7. 0. 6.]
 [6. 5. 5. 8.]]

None

[[0. 8. 4. 6. 3. 7.]
 [0. 6. 6. 5. 5. 8.]]


In [39]:
print(a)
print()
a.reshape(3,-1)

[[0. 8. 4. 6. 3. 7.]
 [0. 6. 6. 5. 5. 8.]]



array([[0., 8., 4., 6.],
       [3., 7., 0., 6.],
       [6., 5., 5., 8.]])

# Stacking together different arrays

In [0]:
#import numpy as np
#np.random.seed(50)
#np.random.randint(1,20,20)

In [41]:
np.random.seed(10)
a = np.floor(10*np.random.random((2,2)))
print(a)
print()

np.random.seed(11)
b = np.floor(10*np.random.random((2,2)))
print(b)
print()

print(np.vstack((a,b)))
print()

print(np.hstack((a,b)))


[[7. 0.]
 [6. 7.]]

[[1. 0.]
 [4. 7.]]

[[7. 0.]
 [6. 7.]
 [1. 0.]
 [4. 7.]]

[[7. 0. 1. 0.]
 [6. 7. 4. 7.]]


In [42]:
from numpy import newaxis
np.column_stack((a,b))    # with 2D arrays

a = np.array([4.,2.])
b = np.array([3.,8.])
print(np.column_stack((a,b)))
print()

print(np.hstack((a,b)))
np.hstack((a,b))
print()

print(a[:,newaxis])
print()

print(np.column_stack((a[:,newaxis], b[:,newaxis])))
print()

print(np.hstack((a[:,newaxis], b[:,newaxis])))
print()

[[4. 3.]
 [2. 8.]]

[4. 2. 3. 8.]

[[4.]
 [2.]]

[[4. 3.]
 [2. 8.]]

[[4. 3.]
 [2. 8.]]



#**Practice from Educative**

In [43]:
import numpy as np  # import the NumPy library

# Initializing a NumPy array
arr = np.array([-1, 2, 5], dtype=np.float32)

# Print the representation of the array
print(repr(arr))
print(arr)

array([-1.,  2.,  5.], dtype=float32)
[-1.  2.  5.]


In [44]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [45]:
arr = np.array([0,0.1,2])  ###UPCASTING
print(repr(arr))

array([0. , 0.1, 2. ])


In the code example below, c is a reference to a while d is a copy. Therefore, changing c leads to the same change in a, while changing d does not change the value of b.

In [46]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))  ##observe the format function
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


In [47]:
arr = np.array([0,1,2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(repr(arr))

int64
array([0., 1., 2.], dtype=float32)


In [48]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError
#np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


In [49]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in an OverflowError
#np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


#**Exercise**

In [50]:
arr = np.array([np.nan,2,3,4,5])
print(repr(arr))
print()

arr2 = arr.copy()
arr2[0] = 10
print(repr(arr2))
print()

float_arr = np.array( [1,5.4,3])
print(float_arr)
float_arr2 = arr2.astype(np.float32)  ##this will work as copy method
print(float_arr2)
float_arr2[0]= 12
print(repr(arr2), repr(float_arr2))
print()

matrix = np.array([[1,2,3], [4,5,6]], dtype=np.float32)
print(repr(matrix))

array([nan,  2.,  3.,  4.,  5.])

array([10.,  2.,  3.,  4.,  5.])

[1.  5.4 3. ]
[10.  2.  3.  4.  5.]
array([10.,  2.,  3.,  4.,  5.]) array([12.,  2.,  3.,  4.,  5.], dtype=float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)


In [51]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)  ##step =2
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


The end of the range is inclusive for **np.linspace**, unless the keyword argument endpoint is set to False. To specify the number of elements, we set the num keyword argument (its default value is 50)

In [52]:
arr = np.linspace(5, 11, num=4)  ##(11-5)/(4-1)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)  ## (11-5) /4
print(repr(arr))

arr = np.linspace(3, 6, num=3, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([3., 4., 5.])
array([ 5,  7,  9, 11], dtype=int32)


In [53]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))
print()


arr2 =  np.arange(81)
reshaped_arr = np.reshape(arr2, (3,-1))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
        43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
        70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])
New shape: (3, 27)


In [54]:
arr = np.arange(8)
arr = arr.reshape((2,4))
print(repr(arr))
print('arr shape:{}'.format(arr.shape))
print()

flattened = arr.flatten()
print(repr(flattened))
print('arr shape:{}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape:(2, 4)

array([0, 1, 2, 3, 4, 5, 6, 7])
arr shape:(8,)


In [0]:
?np.reshape

In [56]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


In [57]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
transposed = np.transpose(arr, axes=(1, 0, 2))
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

#for 3-D data the default axes value is [2, 1, 0]

arr shape: (3, 4, 2)
transposed shape: (4, 3, 2)


In [58]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [59]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


#**EXERCISE**

In [60]:
arr = np.arange(12)
reshaped = arr.reshape((2,3,2))
print(repr(reshaped))

flattened = reshaped.flatten()
print(repr(flattened))

transposed =  np.transpose(reshaped, axes= (1,2,0))
print(repr(transposed))

zeros_arr = np.zeros(5)
print(repr(zeros_arr))

ones_arr = np.ones_like(transposed)
print(repr(ones_arr))

points = np.linspace(-3.5 , 1.5, 101)
print(repr(points))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])
array([0., 0., 0., 0., 0.])
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])
array([-3.5 , -3.45, -3.4 , -3.35, -3.3 , -3.25, -3.2 , -3.15, -3.1 ,
       -3.05, -3.  , -2.95, -2.9 , -2.85, -2.8 , -2.75, -2.7 , -2.65,
       -2.6 , -2.55, -2.5 , -2.45, -2.4 , -2.35, -2.3 , -2.25, -2.2 ,
       -2.15, -2.1 , -2.05, -2.  , -1.95, -1.9 , -1.85, -1.8 , -1.75,
       -1.7 , -1.65, -1.6 , -1.55, -1.5 , -1.45, -1.4 , -1.35, -1.3 ,
       -1.25, -1.2 , -1.15, -1.1 , -1.05, -1.  , -0.95, -0.9 , -0.85,
       -0.8 , -0.75, -0.7 , -0.65, -0.6 , -0.55, -0.5 , -0.45, -0.4 ,
       -0.35, -0.3 , -0.25, -0.2 , -0.15, -0.1 , -0.05,  0.  ,  0.05,
        0.1 ,  0.15,  0.2 , 

In [61]:
arr = np.array([[1, 2], [3, 4]])
print(repr(arr))
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

array([[1, 2],
       [3, 4]])
array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [62]:
def f2c(temps):
  return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


In [63]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
print(repr(arr2))
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[ 1.        , 10.        ],
       [ 2.71828183,  3.14159265]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [65]:
arr = np.array([[1, 2], [3, 4]])
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])

print(repr(np.power(arr,3)))
arr2 = np.array([[10.2, 4], [3, 5]])


# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 1,  8],
       [27, 64]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


In [68]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))  ##dot product

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))  
print(repr(np.matmul(arr4, arr3)))

# This will result in ValueError
#print(repr(np.matmul(arr3, arr3)))  ##must follow matrix multiplication rule

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


#**EXERCISE**


In [82]:
arr =  np.array([[-0.5, 0.8, -0.1],[0.0,-1.2,1.3]])
arr2 = np.array ([[1.2,3.1], [1.2,0.3],[1.5,2.2]])

multiplied = arr * np.pi
print(repr(multiplied))
print()

added = arr+ multiplied
print(repr(added))
#print(repr(np.sum((arr,multiplied), axis=1))) #observe the axis parameter

squared= np.power(added, 2)
print(repr(squared))

exponential = np.exp(squared)
print(repr(exponential))

logged = np.log(arr2)
print(repr(logged))

matmul1 = np.matmul(logged, exponential)
print(repr(matmul1))

matmul2= np.matmul(exponential, logged)
print(repr(matmul2))

array([[-1.57079633,  2.51327412, -0.31415927],
       [ 0.        , -3.76991118,  4.08407045]])

array([[-2.07079633,  3.31327412, -0.41415927],
       [ 0.        , -4.96991118,  5.38407045]])
array([[ 4.28819743, 10.97778541,  0.1715279 ],
       [ 0.        , 24.70001718, 28.98821461]])
array([[7.28350596e+01, 5.85587272e+04, 1.18711726e+00],
       [1.00000000e+00, 5.33434578e+10, 3.88527393e+12]])
array([[ 0.18232156,  1.13140211],
       [ 0.18232156, -1.2039728 ],
       [ 0.40546511,  0.78845736]])
array([[ 1.44108036e+01,  6.03529115e+10,  4.39580713e+12],
       [ 1.20754286e+01, -6.42240618e+10, -4.67776415e+12],
       [ 3.03205327e+01,  4.20590657e+10,  3.06337283e+12]])
array([[ 1.06902790e+04, -7.04197733e+04],
       [ 1.58506868e+12,  2.99914875e+12]])


In [84]:
print(np.random.randint(5))  ## 5 is exclusive
print(np.random.randint(5))
print(np.random.randint(5, high=6)) ##makes 5 inclusive

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))
print(repr(random_arr))

4
4
5
array([[-1,  9],
       [-2,  7]])


In [87]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [89]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)  
#shuffling multi-dimensional arrays only shuffles the first dimension.
print(repr(matrix))

array([2, 5, 4, 1, 3])
array([1, 2, 4, 5, 3])
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])


In [94]:
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))  
#the low and high represent inclusive lower end and exclusive upper end
#default values of 0.0 and 1.0 
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=-3.4, high=5.9,
                             size=(2, 2))))
print()
##Normal (Gaussian distribution)
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
#loc and scale keyword arguments represent the mean and standard deviation
print(repr(np.random.normal(loc=-2.4, scale=4.0,
                            size=(2, 2))))

#Some more inbuilt functions https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html

0.5384246942799851
0.9135058636351059
array([0.36126102, 0.57100856, 0.63783648])
array([[-2.22527157,  3.01890267],
       [ 2.62406942, -0.10836647]])

-0.6845402495469102
5.8959381420206975
array([[-0.41309458, -1.08289679],
       [-2.40475963, -3.6291705 ]])


In [96]:
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=10)))
print(repr(np.random.choice(colors, size=(2, 2),
                            p=[0.8, 0.19, 0.01])))
#p keyword argument denotes the probabilities given to each element

green
array(['green', 'red', 'green', 'blue', 'blue', 'green', 'red', 'green',
       'red', 'green'], dtype='<U5')
array([['blue', 'red'],
       ['blue', 'red']], dtype='<U5')


#**EXERCISE**


In [112]:
random1 = np.random.randint(5)
print(repr(random1))

random_arr = np.random.randint(2, high=10, size= (3,5))
print(repr(random_arr))

random_uniform = np.random.uniform(low=-2.5,high=1.5, size=5)
#print(random_uniform)

random_norm = np.random.normal (loc= 2.0, scale= 3.5, size=(10,5))

choices = ['a', 'b', 'c', 'd']
choice = np.random.choice(choices, p=[0.5, 0.1, 0.2, 0.2])
print(repr(choice))

arr= np.arange(1,6)
print(repr(arr))
np.random.shuffle(arr)
print(repr(arr))

1
array([[3, 6, 7, 3, 6],
       [2, 8, 7, 5, 7],
       [2, 2, 7, 8, 8]])
'c'
array([1, 2, 3, 4, 5])
array([4, 1, 3, 5, 2])


In [113]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))

1
5
array([6, 3])


In [116]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))  ##all values
print(repr(arr[1:])) ##2 to all
print(repr(arr[2:4])) ##3, 4
print(repr(arr[:-1]))  ##1 to 4
print(repr(arr[-2:]))  ##4 to all : got this wrong

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [118]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))  ##all
print(repr(arr[1:])) ##1st row  ##got this wrong
print(repr(arr[:, -1]))  ##all rows, last column
print(repr(arr[:, 1:]))  ##all rows; 2 and 3 columns
print(repr(arr[0:1, 1:])) ##first row; 2,3 columns
print(repr(arr[0, 1:]))  ##first row,  2,3 columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


In [122]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])

print(arr[0])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))
print()
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))  ## column wise
print(repr(np.argmin(arr, axis=1)))  ##row wise
print(repr(np.argmax(arr, axis=-1)))  ## axis=-1 is equivalent to axis=1

[-2 -1 -3]
2
1
5

array([2, 0, 1])
array([2, 2, 0])
array([2, 2, 0])


#**EXERCISE**

In [0]:
def direct_index(data):
  # CODE HERE
  elem = data[1,2]
  return elem

def slice_data(data):
  slice1 = data[:,1:]
  slice2 = data[:3,:-2]
  return(slice1, slice2)

def argmin_data(data):
  argmin_all= np.argmin(data)
  argmin1 = np.argmin(data, axis=1)
  return (argmin_all,argmin1)

def argmax_data(data):
  argmax_neg1= np.argmax(data, axis=-1)
  return argmax_neg1

In [124]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))
# Negated from the previous step
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


In [125]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


In [126]:
print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

(array([0, 2]),)
(array([1, 3]),)
array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])


In [127]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-2, -5], [-1, -8]])
print(repr(np.where(np_filter, positives, negatives)))

#When we use 3 arguments, the first argument is still the boolean array. 
#However, the next two arguments represent the True replacement values and 
#the False replacement values, respectively. The output of the function now 
#becomes an array with the same shape as the first argument.

np_filter = positives > 2
print(repr(np.where(np_filter, positives, negatives)))

np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))

array([[ 1, -5],
       [-1,  4]])
array([[-2, -5],
       [ 3,  4]])
array([[-2, -5],
       [-1, -8]])


In [128]:
#if we wanted to use a constant replacement value, e.g. -1, 
#we could incorporate broadcasting

np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
print(repr(np.where(np_filter, positives, -1)))

array([[ 1, -1],
       [-1,  4]])


In [129]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(np.any(arr > 0))
print(np.all(arr > 0))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
True
False


In [130]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(repr(np.any(arr > 0, axis=0)))
print(repr(np.any(arr > 0, axis=1)))
print(repr(np.all(arr > 0, axis=1)))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
array([ True,  True,  True])
array([False,  True,  True])
array([False, False,  True])


In [131]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
has_positive = np.any(arr > 0, axis=1)
print(has_positive)
print(repr(arr[np.where(has_positive)]))

[False  True  True]
array([[ 4,  5, -6],
       [ 3,  9,  1]])


#**EXERCISE**

In [0]:
def get_positives(data):
  x_ind, y_ind = np.where(data>0)
  return data[x_ind,y_ind] 

##REPLACING ZEROS IN AN ARRAY
def replace_zeros(data):
  zeros = np.zeros_like(data)
  zero_replace = np.where(data>0, data, zeros)
  return zero_replace

def replace_neg_one(data):
  neg_one_replace = np.where(data>0, data, -1)
  return neg_one_replace

def coin_flip_filter(data):
  coin_flips=np.random.randint(2, size=data.shape)
  bool_coin_flips = coin_flips.astype(np.bool)
  one_replace = np.where(bool_coin_flips, data, 1)
  return one_replace




In [136]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr.min())
print(arr.max())

print(repr(arr.min(axis=0)))
print(repr(arr.max(axis=-1)))


-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


In [137]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(repr(np.median(arr, axis=-1)))

2.0
977.3333333333334
1.0
array([ 3.,  1., -2.])


#**EXERCISE**

In [0]:
def get_min_max(data):
  overall_min = data.min()
  overall_max= data.max()
  return (overall_min, overall_max)

def col_min(data):
  min0 = data.min(axis=0)
  return min0

def basic_stats(data):
  mean = np.mean(data)
  median = np.median(data)
  var = np.var(data)
  return (mean, median,var)

In [138]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.sum(arr))
print(repr(np.sum(arr, axis=0)))
print(repr(np.sum(arr, axis=1)))

18
array([ -2,  73, -53])
array([ 75, -56,  -1])


In [139]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis=0)))
print(repr(np.cumsum(arr, axis=1)))

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


In [140]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])
print(repr(np.concatenate([arr1, arr2])))
print(repr(np.concatenate([arr1, arr2], axis=1)))
print(repr(np.concatenate([arr2, arr1], axis=1)))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])


#**EXERCISE**

In [0]:
def get_sums(data):
  total_sum = np.sum(data)
  col_sum = np.sum(data, axis=0)
  return (total_sum, col_sum)

def get_cumsum(data):
  row_cumsum = np.cumsum(data, axis=1)
  return(row_cumsum)

def concat_arrays(data1, data2):
  col_concat = np.concatenate([data1, data2], axis=0)
  row_concat = np.concatenate([data1, data2], axis=1)
  return (col_concat, row_concat)

In [0]:
arr = np.array([1, 2, 3])
# Saves to 'arr.npy'
np.save('arr.npy', arr)
# Also saves to 'arr.npy'
np.save('arr', arr)

In [143]:
arr = np.array([1, 2, 3])
np.save('arr.npy', arr)
load_arr = np.load('arr.npy')
print(repr(load_arr))

# Will result in FileNotFoundError
#load_arr = np.load('arr')

array([1, 2, 3])


#**EXERCISE**


In [0]:
def save_points(save_file):
  points = np.random.uniform(low=-2.5, high=2.5, size=(100,2))
  np.save(save_file, points)
