# **Data standardization**

The standard format refers to data that has 0 mean and unit variance (i.e. standard deviation = 1), and the process of converting data into this format is called data standardization.

Data standardization is a relatively simple process. For each data value, x, we subtract the overall mean of the data, μ, then divide by the overall standard deviation, σ. The new value, z, represents the standardized data value. Thus, the formula for data standardization is:

z = (x-μ) / ​​σ

In [1]:
import sklearn
import numpy as np
pizza_data = np.array([[2100,   10,  800],
       [2500,   11,  850],
       [1800,   10,  760],
       [2000,   12,  800],
       [2300,   11,  810]])

print(pizza_data)
print('{}\n'.format(repr(pizza_data)))

from sklearn.preprocessing import scale
col_standardized = scale(pizza_data)
print('{}\n'.format(col_standardized))

col_means = col_standardized.mean(axis=0).round(decimals=3)
print(col_means)
print()
col_std= col_standardized.std(axis=0)
print(col_std)


[[2100   10  800]
 [2500   11  850]
 [1800   10  760]
 [2000   12  800]
 [2300   11  810]]
array([[2100,   10,  800],
       [2500,   11,  850],
       [1800,   10,  760],
       [2000,   12,  800],
       [2300,   11,  810]])

[[-0.16552118 -1.06904497 -0.1393466 ]
 [ 1.4896906   0.26726124  1.60248593]
 [-1.40693001 -1.06904497 -1.53281263]
 [-0.57932412  1.60356745 -0.1393466 ]
 [ 0.66208471  0.26726124  0.2090199 ]]

[ 0. -0.  0.]

[1. 1. 1.]


# **Data Range**

x_{prop} = (x - d_{min}) / (d_{max} - d_{min})

x_{scale} = x_{prop} * (r_{max} - r_{min}) + r_{min}
​​

The **MinMaxScaler** transformer performs the range compression using the previous formula. Specifically, it scales each feature (column) of the data to a given range (where the default range is [0, 1])

In [2]:
data =  np.array([[ 1.2,  3.2],
       [-0.3, -1.2],
       [ 6.5, 10.1],
       [ 2.2, -8.4]])

print(data)

from sklearn.preprocessing import MinMaxScaler
default_scaler = MinMaxScaler() # the default range is [0,1]
transformed = default_scaler.fit_transform(data)
print('{}\n'.format(repr(transformed)))

custom_scalar =  MinMaxScaler(feature_range=(-2,3))
transformed = custom_scalar.fit_transform(data)
print(transformed)

[[ 1.2  3.2]
 [-0.3 -1.2]
 [ 6.5 10.1]
 [ 2.2 -8.4]]
array([[0.22058824, 0.62702703],
       [0.        , 0.38918919],
       [1.        , 1.        ],
       [0.36764706, 0.        ]])

[[-0.89705882  1.13513514]
 [-2.         -0.05405405]
 [ 3.          3.        ]
 [-0.16176471 -2.        ]]


In [3]:
data =  np.array([[ 1.2,  3.2],
       [-0.3, -1.2],
       [ 6.5, 10.1],
       [ 2.2, -8.4]])

new_data = np.array([[ 1.2, -0.5],
       [ 5.3,  2.3],
       [-3.3,  4.1]])


from sklearn.preprocessing import MinMaxScaler
default_scaler = MinMaxScaler()
transformed = default_scaler.fit_transform(new_data)
print(transformed)
print()

from sklearn.preprocessing import MinMaxScaler
default_scaler = MinMaxScaler()
default_scaler.fit(data)
transformed = default_scaler.transform(new_data)
print(transformed)


[[0.52325581 0.        ]
 [1.         0.60869565]
 [0.         1.        ]]

[[ 0.22058824  0.42702703]
 [ 0.82352941  0.57837838]
 [-0.44117647  0.67567568]]


In the code above it scales the new_data array to the range [0, 1], based on the (column-wise) minimum and maximum values from the data array in the original code example.

# **Robust Scaling**

* An outlier is a data point that is significantly further away from the other data points. 

* Data standardization uses each feature's mean and standard deviation, while ranged scaling uses the maximum and minimum feature values, meaning that they're both susceptible to being skewed by outlier values.

* We can robustly scale the data, i.e. avoid being affected by outliers, by using use the data's median and Interquartile Range (IQR).

RobustScaler transforms the feature vector by subtracting the median and then dividing by the interquartile range (75% value — 25% value). Like MinMaxScaler, our feature with large values — normal-big — is now of similar scale to the other features. Note that RobustScaler does not scale the data into a predetermined interval like MinMaxScaler. It does not meet the strict definition of scale I introduced earlier.
Note that the range for each feature after RobustScaler is applied is larger than it was for MinMaxScaler.
Use RobustScaler if you want to reduce the effects of outliers, relative to MinMaxScaler.


In [4]:
data = np.array([[ 1.2,  2.3],
       [ 2.1,  4.2],
       [-1.9,  3.1],
       [-2.5,  2.5],
       [ 0.8,  3. ],
       [ 6.3,  2.1],
       [-1.5,  2.7],
       [ 1.4,  2.9],
       [ 1.8,  3.2]])

print(data)
print()

from sklearn.preprocessing import RobustScaler
robust_scaler = RobustScaler()
transformed = robust_scaler.fit_transform(data)
print(transformed)

[[ 1.2  2.3]
 [ 2.1  4.2]
 [-1.9  3.1]
 [-2.5  2.5]
 [ 0.8  3. ]
 [ 6.3  2.1]
 [-1.5  2.7]
 [ 1.4  2.9]
 [ 1.8  3.2]]

[[ 0.         -1.        ]
 [ 0.27272727  2.16666667]
 [-0.93939394  0.33333333]
 [-1.12121212 -0.66666667]
 [-0.12121212  0.16666667]
 [ 1.54545455 -1.33333333]
 [-0.81818182 -0.33333333]
 [ 0.06060606  0.        ]
 [ 0.18181818  0.5       ]]


In [0]:
?RobustScaler

# **Normalizing Data**

So far, each of the scaling techniques we've used has been applied to the data features (i.e. columns). However, in certain cases we want to scale the individual data observations (i.e. rows)When clustering data we need to apply L2 normalization to each row, in order to calculate cosine similarity scores. 

In [6]:
data = np.array([[4, 1, 2, 2],
       [3, 4, 0, 0],
       [7, 5, 9, 2]])

print(data,'\n')

from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
transformed = normalizer.fit_transform(data)
print(transformed)

[[4 1 2 2]
 [3 4 0 0]
 [7 5 9 2]] 

[[0.8        0.2        0.4        0.4       ]
 [0.6        0.8        0.         0.        ]
 [0.55513611 0.39652579 0.71374643 0.15861032]]


# **Data Imputation**

We often have to deal with data that contains missing values. Sometimes, if the dataset is missing too many values, we just don't use it. However, if only a few of the values are missing, we can perform data imputation to substitute the missing data with some other value(s).

There are many different methods for data imputation. In scikit-learn, the SimpleImputer transformer performs four different data imputation methods.

The four methods are:
* Using the mean value
* Using the median value
* Using the most frequent value
* Filling in missing values with a constant

In [7]:
data = np.array([[ 1.,  2., np.nan,  2.],
       [ 5., np.nan,  1.,  2.],
       [ 4., np.nan,  3., np.nan],
       [ 5.,  6.,  8.,  1.],
       [np.nan,  7., np.nan,  0.]])
print(data,'\n')

from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer()
transformed = imp_mean.fit_transform(data)
print(transformed)

#mean is applied across the individual feature and the no.of values for each 
#is taken omitting the count of nan values

[[ 1.  2. nan  2.]
 [ 5. nan  1.  2.]
 [ 4. nan  3. nan]
 [ 5.  6.  8.  1.]
 [nan  7. nan  0.]] 

[[1.   2.   4.   2.  ]
 [5.   5.   1.   2.  ]
 [4.   5.   3.   1.25]
 [5.   6.   8.   1.  ]
 [3.75 7.   4.   0.  ]]


In [8]:
from sklearn.impute import SimpleImputer
imp_median = SimpleImputer(strategy='median')  ##median should always be in lower case
transformed = imp_median.fit_transform(data)
print(transformed,'\n')

from sklearn.impute import SimpleImputer
imp_frequent = SimpleImputer(strategy='most_frequent')
transformed=imp_frequent.fit_transform(data)
print(transformed,'\n')

from sklearn.impute import SimpleImputer
imp_constant = SimpleImputer(strategy='constant', fill_value= 1)
transformed = imp_constant.fit_transform(data)
print(transformed)

[[1.  2.  3.  2. ]
 [5.  6.  1.  2. ]
 [4.  6.  3.  1.5]
 [5.  6.  8.  1. ]
 [4.5 7.  3.  0. ]] 

[[1. 2. 1. 2.]
 [5. 2. 1. 2.]
 [4. 2. 3. 2.]
 [5. 6. 8. 1.]
 [5. 7. 1. 0.]] 

[[1. 2. 1. 2.]
 [5. 1. 1. 2.]
 [4. 1. 3. 1.]
 [5. 6. 8. 1.]
 [1. 7. 1. 0.]]


The **SimpleImputer** object only implements the four imputation methods shown above.

There are also more advanced imputation methods such as **k-Nearest Neighbors** (filling in missing values based on similarity scores from the kNN algorithm) and **MICE** (applying multiple chained imputations, assuming the missing values are randomly distributed across observations).

# **PCA**

Most datasets contain a large number of features, some of which are redundant or not informative. For example, in a dataset of basketball statistics, the total points and points per game for a player will (most of the time) tell the same story about the player's scoring prowess.

When a dataset contains these types of correlated numeric features, we can perform principal component analysis (PCA) for **dimensionality reduction**.


In [9]:
data = np.array([[ 1.5,  3. ,  9. , -0.5,  1. ],
       [ 2.2,  4.3,  3.5,  0.6,  2.7],
       [ 3. ,  6.1,  1.1,  1.2,  4.2],
       [ 8. , 16. ,  7.7, -1. ,  7.1]])

print(data, '\n')

from sklearn.decomposition import PCA
pca_obj = PCA() # The value of n_component will be 4. As m is 5 and default is always m-1
pc = pca_obj.fit_transform(data).round(1)
print(pc, '\n')

pca_obj = PCA(n_components=3)
pc = pca_obj.fit_transform(data).round(3)
print('{}\n'.format(repr(pc)))

pca_obj = PCA(n_components=2)
pc = pca_obj.fit_transform(data).round(3)
print('{}\n'.format(repr(pc)))

[[ 1.5  3.   9.  -0.5  1. ]
 [ 2.2  4.3  3.5  0.6  2.7]
 [ 3.   6.1  1.1  1.2  4.2]
 [ 8.  16.   7.7 -1.   7.1]] 

[[-4.9  4.6 -0.   0. ]
 [-3.8 -1.3  0.1  0. ]
 [-1.9 -4.2 -0.1  0. ]
 [10.5  0.9  0.   0. ]] 

array([[-4.8600e+00,  4.6300e+00, -4.7000e-02],
       [-3.7990e+00, -1.3180e+00,  1.2700e-01],
       [-1.8630e+00, -4.2260e+00, -8.9000e-02],
       [ 1.0522e+01,  9.1400e-01,  9.0000e-03]])

array([[-4.86 ,  4.63 ],
       [-3.799, -1.318],
       [-1.863, -4.226],
       [10.522,  0.914]])



# **Labeled Data**

In [10]:
from sklearn.datasets import load_breast_cancer
bc = load_breast_cancer()
print(bc.data,'\n')
print(bc.data.shape,'\n')

print(bc.target,'\n')
print('Labels Shape', bc.target.shape, '\n')

print(bc.target_names, '\n')

malignant = bc.data[bc.target == 0]
print('Malignant Shape: ', malignant.shape, '\n')

benign = bc.data[bc.target == 1]
print('Benign Shape: ', benign.shape, '\n')

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] 

(569, 30) 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 

# **Data Modeling**

When creating these models, data scientists need to figure out the optimal hyperparameters to use. Hyperparameters are values that we set when creating a model, e.g. certain constant coefficients used in the model's calculations

##**Linear regression**

In [11]:
pizza_data = np.array([[2100,  800],
       [2500,  850],
       [1800,  760],
       [2000,  800],
       [2300,  810]])
#pizza_data represents the number of calories and 
#the second column represents net weight (in grams)

pizza_prices = np.array([10.99, 12.5,9.99, 10.99, 11.99])

print(pizza_data, '\n\n', pizza_prices)

from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(pizza_data, pizza_prices)

[[2100  800]
 [2500  850]
 [1800  760]
 [2000  800]
 [2300  810]] 

 [10.99 12.5   9.99 10.99 11.99]


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

The R2 value(coefficient of determination) tells us how close of a fit the linear model is to the data, or in other words, how good of a fit the model is for the data.

In [12]:
new_pizzas = np.array([[2000, 820], [2200,830]])

price_predicts =  reg.predict(new_pizzas)
print(price_predicts,'\n')

print('Coefficients: ', reg.coef_, '\n')
print('Intercept: ', reg.intercept_, '\n')

r2 = reg.score(pizza_data, pizza_prices)
print('R2: ',r2)

[10.86599206 11.55111111] 

Coefficients:  [0.00330913 0.00232937] 

Intercept:  2.3376587301587346 

R2:  0.9758349388652625


## **Ridge Regression**

Real life data tends to have noise, and will often have some linearly correlated features in the dataset, we combat this by performing regularization.

For ordinary least squares regression, the goal is to find the weights (coefficients) for the linear model that minimize the sum of squared residuals:
                      **∑(x_i *w− y_i)2**

For regularization, the goal is to not only minimize the sum of squared residuals, but to do this with coefficients as small as possible. The smaller the coefficients, the less susceptible they are to random noise in the data. The most commonly used form of regularization is ridge regularization.
​


In [43]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=0.1)
reg.fit(pizza_data, pizza_prices)
print('Coefficients: {}\n'.format(repr(reg.coef_)))
print('Intercept: {}\n'.format(reg.intercept_))
r2 = reg.score(pizza_data, pizza_prices)
print('R2: {}\n'.format(r2))
#new_pizzas = np.array([[2000, 820], [2200,830]])
#print(repr(reg.predict(new_pizzas)))


##CROSS VALIDATED RIDGE REGRESSION
from sklearn import linear_model
alphas = [0.1, 0.2, 0.3]
reg = linear_model.RidgeCV(alphas=alphas)
reg.fit(pizza_data, pizza_prices)
print('Coefficients: ',reg.coef_,'\n')
print('Intercept: ', reg.intercept_, '\n')
print('Choosen Alpha: ',reg.alpha_, '\n')

Coefficients: array([0.00330919, 0.0023288 ])

Intercept: 2.337978289647138

R2: 0.9758349388362841

Coefficients:  [0.00330932 0.00232767] 

Intercept:  2.3386168534481815 

Choosen Alpha:  0.3 



## **LASSO Regression**

While ridge regularization uses an L2 norm penalty term, another regularization method called LASSO uses an L1 norm for the weights penalty term.

In [14]:
import numpy as np

data = np.array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

labels = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) 

print(data.shape,'\n')
print(labels.shape, '\n')
print(np.unique(labels),'\n')

from sklearn import linear_model
reg = linear_model.Lasso(alpha=0.1)
reg.fit(data,labels)

print('Coefficients: ',reg.coef_, '\n')
print('Intercept: ', reg.intercept_, '\n')
print('R2: ',reg.score(data,labels),'\n\n\n')


##CV LASSO REGRESSION
from sklearn import linear_model
alphas= [0.1,0.3,0.4 ]
reg= linear_model.LassoCV(alphas=alphas)
reg.fit(data,labels)

print('Coefficients: ',reg.coef_, '\n')
print('Intercept: ', reg.intercept_, '\n')
print('Alpha choosen: ',reg.alpha_,'\n')
print('R2: ',reg.score(data,labels))

(150, 4) 

(150,) 

[0 1 2] 

Coefficients:  [ 0.         -0.          0.40830957  0.        ] 

Intercept:  -0.5346995583185636 

R2:  0.895831189504504 



Coefficients:  [ 0.         -0.          0.40830957  0.        ] 

Intercept:  -0.5346995583185636 

Alpha choosen:  0.1 

R2:  0.895831189504504


## **Bayesian Regression**

Another way to optimize the hyperparameters of a regularized regression model is with Bayesian techniques.

* In Bayesian statistics, the main idea is to make certain assumptions about the probability distributions of a model's parameters before being fitted on data. These initial distribution assumptions are called priors for the model's parameters

* There are two hyperparameters to optimize: α and λ. 

* The α hyperparameter serves the same exact purpose as it does for regular ridge regression; namely, it acts as a scaling factor for the penalty term. 

* The λ hyperparameter acts as the precision of the model's weights. Basically, the smaller the λ value, the greater the variance between the individual weight values.

* Both the α and λ hyperparameters have gamma distribution priors, defined by a shape parameter and scale parameter.


In [15]:
# predefined dataset from previous chapter
print('Data shape: {}\n'.format(data.shape))
print('Labels shape: {}\n'.format(labels.shape))

from sklearn import linear_model
reg = linear_model.BayesianRidge() 
reg.fit(data, labels)
print('Coefficients: {}\n'.format(repr(reg.coef_)))
print('Intercept: {}\n'.format(reg.intercept_))
print('R2: {}\n'.format(reg.score(data, labels)))
print('Alpha: {}\n'.format(reg.alpha_))
print('Lambda: {}\n'.format(reg.lambda_))

#The default value for each of the four gamma parameters is 10-6.

Data shape: (150, 4)

Labels shape: (150,)

Coefficients: array([-0.11174556, -0.03900746,  0.24329606,  0.57345867])

Intercept: 0.17024073782276639

R2: 0.9303454947351278

Alpha: 20.984220720919353

Lambda: 9.539435179662341



## **Logistic Regression**

The logistic regression model, despite its name, is actually a linear model for classification. It is called logistic regression because it performs regression on logits, which then allows us to classify the data based on model probability predictions.



In [16]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import linear_model

data=load_breast_cancer()
X = data['data']
Y = data['target']
feature_names = data["feature_names"]
df = pd.DataFrame(X, columns=feature_names)
print(df)

X_train, X_test, Y_train, Y_test = train_test_split(df, Y, test_size=0.2)

reg=linear_model.LogisticRegression()
reg.fit(X_train, Y_train)
pred = reg.predict(X_test)


     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [31]:
#@title
data = np.array([[ 1.16014257e+03, -2.93917544e+02,  4.85783976e+01,
        -8.71197531e+00],
       [ 1.26912244e+03,  1.56301818e+01, -3.53945342e+01,
         1.78612832e+01],
       [ 9.95793889e+02,  3.91567432e+01, -1.70975298e+00,
         4.19934010e+00],
       [-4.07180803e+02, -6.73803198e+01,  8.67284783e+00,
        -1.17598673e+01],
       [ 9.30341180e+02,  1.89340742e+02,  1.37480074e+00,
         8.49918256e+00],
       [-2.11591259e+02, -7.98774463e+01, -1.47945698e+00,
        -2.89929532e+00],
       [ 8.21210900e+02, -4.71496699e+01, -3.22549991e+01,
         3.03846993e-01],
       [-2.50899776e+01, -7.41860146e+01,  1.17907139e+01,
        -7.10824707e+00],
       [-1.91292834e+02, -4.21264896e+01, -6.29131241e+00,
        -1.05373520e+01],
       [-2.38292863e+02, -6.53865069e+01, -3.63214959e+00,
        -1.26091476e+01],
       [ 3.04687818e+02, -1.77250598e+01, -1.70745476e+01,
        -4.60196868e+00],
       [ 4.24361128e+02, -1.09220300e+02, -9.91130269e+00,
        -4.25468787e+00],
       [ 6.34514335e+02,  1.67205436e+02,  3.73890987e+01,
        -1.99708730e+01],
       [ 6.30426906e+01,  1.11677576e+02, -8.52477755e+00,
        -4.61617832e+00],
       [-1.96441210e+02,  2.96579342e+01, -1.20870168e+01,
        -1.40328736e+01],
       [ 5.60046828e+01, -2.91483486e+01, -1.26167165e+01,
        -1.87127876e+01],
       [ 2.35858120e+02, -1.08425643e+02, -7.82705331e+00,
        -4.37725899e+00],
       [ 4.47392780e+02, -1.02151566e+02, -1.15165542e+01,
        -7.96675194e+00],
       [ 1.61509345e+03, -2.70333351e+02, -1.55425179e+01,
         4.88194292e+00],
       [-1.91621045e+02,  1.22591777e+01, -6.24101956e+00,
         3.58803395e+00],
       [-2.85051275e+02,  1.45573619e+01, -1.01779712e+01,
         1.48301490e+00],
       [-6.83583952e+02, -3.25761260e+01,  1.50953427e+01,
         1.25767805e+01],
       [ 1.12560459e+02, -9.16055399e+00, -2.98236877e+00,
        -4.76669860e+00],
       [ 1.87373312e+03, -2.60196055e+02, -4.72163735e+01,
         1.47193360e+01],
       [ 1.27373066e+03, -4.79321419e+02, -5.78243128e+00,
        -2.00536448e+00],
       [ 6.34879769e+02, -7.99316763e+01,  3.46864274e+01,
        -9.92533251e+00],
       [ 8.59184126e+00, -1.69844205e+01, -2.15611646e+01,
        -1.46441037e+01],
       [ 6.77784526e+02,  1.04824662e+02,  1.46601552e+01,
        -1.37743734e+00],
       [ 3.73719881e+02, -1.35334763e+02, -1.93671690e+01,
        -2.21475479e+01],
       [ 4.53678089e+02,  7.73999547e+01, -5.43888370e+00,
         1.57463187e+00],
       [ 9.03981279e+02, -3.89101877e+01,  1.33043208e+01,
        -1.25862720e+01],
       [-1.03689312e+02, -1.87685324e+02,  6.17207331e+00,
        -1.27720032e+01],
       [ 5.24945203e+02, -3.12276266e+01, -2.30642540e+00,
        -6.91637032e+00],
       [ 1.06217159e+03, -5.02401489e+01, -3.11894223e+01,
        -7.61086868e-01],
       [ 4.04385934e+02, -6.70795449e+01, -2.80482761e+01,
        -1.24037786e+00],
       [ 4.10049756e+02,  2.86413190e+00, -1.88080084e+01,
        -4.96812536e+00],
       [-8.06577946e+01,  2.33635273e+01, -1.25963325e+01,
        -1.23261167e+01],
       [-3.55877850e+02,  6.15355662e+01, -6.24278540e+00,
         4.97009050e+00],
       [-1.28973156e+02,  1.32606887e+02,  7.19977911e+01,
        -7.48590001e+00],
       [-1.70245723e+02, -9.05487530e+00, -1.32354536e+01,
        -6.42842058e+00],
       [-1.27994761e+02, -3.06874982e+01, -1.27572595e+01,
        -3.30232317e+00],
       [-4.62028008e+02, -5.28025874e+01,  2.20802016e+00,
        -8.65914058e+00],
       [ 8.97027427e+02, -1.51720525e+01,  1.18480146e+01,
        -2.47856452e+01],
       [-3.43752015e+01, -1.07672761e+02, -7.22036686e+00,
        -6.36487768e+00],
       [-1.84707363e+02, -3.30806589e+01, -1.62300917e+01,
        -7.39315767e+00],
       [ 8.07564573e+02,  4.27138034e+00, -1.40419057e+01,
         3.02222036e+00],
       [-7.83838668e+02, -5.68265560e+01,  1.36578692e+01,
         1.09296615e+01],
       [-1.66757183e+02, -4.00146842e+01, -7.06109816e+00,
        -3.73455088e+00],
       [-3.62699507e+02, -2.12153952e+01, -1.07669483e-02,
         3.28446143e+00],
       [-2.05111744e+02,  1.39402873e+01, -9.28633666e+00,
        -5.79381343e+00],
       [-4.30034080e+02, -5.31968509e+00,  1.24279152e+01,
        -5.39243111e-01],
       [-2.35893530e+02,  4.51306052e+01, -1.29787658e+01,
         2.31291479e+00],
       [-4.16469507e+02, -2.57068803e+00,  8.11389123e-01,
         4.24603912e+00],
       [ 5.76360308e+02,  9.54517242e+01,  2.54662312e+01,
        -1.34511291e+00],
       [ 1.57404079e+02, -2.81567475e+01, -1.94426831e+01,
        -3.91171713e+00],
       [-4.48982719e+02, -1.61412001e+01,  8.71961825e+00,
         2.90015920e+00],
       [ 1.34213857e+03, -2.31148270e+02, -1.04307150e+01,
         7.36886694e+00],
       [ 9.09989494e+01, -5.26642487e+01, -5.67308340e+00,
        -6.30521151e+00],
       [-2.86145436e+02,  2.39332982e+01,  8.72480524e+00,
         2.24121978e+00],
       [-7.44091835e+02, -5.43008275e+01,  1.16462573e+01,
         1.57981993e+01],
       [-6.16729721e+02, -2.77352453e+01,  2.98944562e+01,
         7.67956065e+00],
       [-7.45600808e+02, -5.61645430e+01,  2.11560950e+01,
         3.33066292e+00],
       [ 6.44083862e+01, -4.84699559e+01,  1.59341308e+01,
        -1.20895910e+01],
       [-6.93961699e+02, -4.12211876e+01,  2.33549407e+01,
         8.65853909e+00],
       [-7.42768046e+01, -1.37543071e+02,  1.84438409e-01,
        -1.13008668e+01],
       [ 4.51754297e+01, -1.15226590e+01, -8.55384638e+00,
        -9.84297373e+00],
       [-6.72376704e+02, -4.48824624e+01,  1.23922172e+01,
         2.27743436e-01],
       [-4.90879529e+02, -8.46032004e+00,  5.83190198e+00,
         3.58049869e+00],
       [-6.87223199e+02, -5.77959675e+01,  1.71429426e+01,
         6.52417979e+00],
       [-3.58981873e+02,  3.87104912e+01, -1.78264687e+00,
         6.02400891e+00],
       [ 1.09240105e+03, -1.05035759e+02, -4.62868220e+00,
        -3.10131775e-01],
       [-7.24662583e+02, -4.22281052e+01,  2.71788347e+01,
         1.06323867e+01],
       [ 8.28581198e+02, -1.80667869e+02, -1.63679024e+01,
        -4.90661848e+00],
       [-9.55563616e+01, -2.50173428e+01, -1.22069960e+01,
        -1.29020507e+00],
       [-3.27215523e+02, -1.75942478e+01, -2.09143500e+00,
         2.91946466e+00],
       [ 3.79602387e+02, -3.82014228e+01,  1.77209138e+01,
        -2.54585059e+00],
       [-2.85278119e+02,  6.13464750e+01,  8.13194666e+00,
         8.63663265e+00],
       [ 8.11390005e+02, -7.74173801e+01,  4.93296884e+01,
        -1.24981379e+00],
       [ 9.46865858e+02,  1.20574151e+02,  1.99971842e+01,
        -2.07226117e+01],
       [-2.99250196e+02,  7.07830339e+00, -3.40176993e+00,
         4.68692850e-01],
       [-4.36503939e+02, -3.24503345e+01,  8.71941583e+00,
        -4.84400058e+00],
       [-2.98362656e+02,  2.26721773e+01, -1.14690119e+01,
        -1.22165173e+00],
       [ 2.07740594e+03,  1.73518339e+02, -3.71190264e+01,
         1.62402683e+00],
       [ 6.06824327e+02,  1.91923370e+02, -9.27376350e+00,
        -9.62864019e+00],
       [-3.78661386e+02, -1.88409957e+01, -2.81894593e+00,
         1.98616937e+00],
       [ 8.38236034e+02, -1.54744078e+01, -6.61734129e+00,
        -5.69754818e-01],
       [-6.44630843e+01,  3.16412663e+01,  1.17919973e+00,
        -7.17996635e+00],
       [ 8.54613799e+02, -2.51845307e+01, -3.05258796e+01,
        -1.87669099e+00],
       [-3.60500123e+02, -2.82856687e+00,  2.91111943e-01,
        -6.05716794e+00],
       [-6.67916271e+01,  3.78367726e+01,  5.33179543e+00,
        -5.87739389e-01],
       [-6.19424844e+01,  4.66727503e+01, -3.66001542e+00,
        -3.49729690e+00],
       [-4.73708321e+00,  8.87035158e+01, -1.15768112e+01,
        -2.14487507e+00],
       [-9.65562522e+01, -6.23546964e+01,  1.80397272e+00,
         2.10577663e+00],
       [-2.07477212e+02,  8.71040658e+00, -3.79321111e+00,
        -8.48943518e-01],
       [ 1.50753037e+02, -3.12663605e+01, -2.41685308e+00,
        -6.27424201e+00],
       [ 1.06220376e+03,  6.98321701e+01, -1.18439420e+01,
         1.62761400e+00],
       [-4.36373547e+02,  2.57538378e+01,  8.64931632e+00,
         3.47337880e+00],
       [-6.28769296e+02, -4.16555921e+01,  1.59682493e+01,
         3.32667810e+00],
       [-4.42121250e+02, -1.62573992e+01,  7.15226094e-01,
         8.02425720e+00],
       [-5.31055528e+01,  1.75963869e+01, -1.14555805e+01,
        -6.52107227e+00],
       [-1.50970253e+01, -7.53359463e+01,  3.58447802e+00,
        -9.01880787e+00],
       [-8.63142308e+02, -7.73995206e+01,  2.04933156e+01,
         1.60463434e+01],
       [-3.88027039e+02,  4.61318988e+00, -3.93559135e+00,
        -2.03620244e+00],
       [-6.31210194e+02, -3.58248172e+01,  7.36393496e+00,
         1.20525963e+00],
       [-5.75375594e+02, -2.48922214e+01,  1.56196533e+01,
         2.51192648e+00],
       [-1.10478362e+02, -7.87647611e+01,  4.92626398e-01,
        -1.08073340e+00],
       [-4.33855875e+02, -2.12105206e+01,  4.50268272e+00,
        -2.71003630e+00],
       [-3.87258589e+02,  1.34995598e+01, -9.47142280e+00,
         1.09343895e+00],
       [ 1.71641922e+03, -3.65487344e+01,  3.28118506e+01,
        -1.14259359e+01],
       [-4.45594260e+02, -3.31791408e+01,  1.21620974e+00,
        -2.09161171e+00],
       [-6.29930932e+02, -4.56688144e+01,  1.87446671e+01,
         4.51688402e+00],
       [-3.93495618e+02,  3.41547739e+01,  1.53805537e+00,
        -3.32619386e+00],
       [-1.59550090e+02,  6.82041740e+01, -3.83435933e+00,
        -7.32192555e+00],
       [-6.00774542e+02, -1.16916160e+01,  1.36682664e+01,
         2.33076789e+00],
       [-7.32350558e+02, -5.37548691e+01,  1.10530381e+01,
         9.02377853e+00],
       [-3.67752309e+02, -3.06879233e+01,  5.26360841e+00,
        -1.02152070e+00],
       [-7.36744006e+02, -3.38095510e+01,  1.91834220e+01,
         9.33062982e+00],
       [ 1.98250721e+02, -8.75101414e+01, -1.07575231e+01,
        -6.26683487e+00],
       [ 4.02217870e+02, -9.37147014e+01, -4.17385398e+00,
        -5.80966309e+00],
       [ 4.95886901e+02,  8.24187856e+01, -1.42956288e+01,
         2.44467158e+00],
       [-4.48932547e+02, -2.32226327e+01, -4.10681098e+00,
         9.34312682e+00],
       [ 7.93467305e+02,  1.44327023e+01,  5.94044351e+00,
         2.88581862e+00],
       [ 1.60479840e+03,  3.28667570e+02,  1.01020544e+02,
        -4.13801648e+00],
       [-1.23524596e+02,  5.83016390e+01, -9.71674718e+00,
         6.44364273e+00],
       [-2.66553320e+02,  4.22630651e+01, -1.09206672e+01,
         3.97713501e+00],
       [-1.67747128e+02,  2.36557326e+01, -1.33528722e+01,
         1.51523698e+00],
       [-7.06506347e+01, -5.40974416e+01, -1.74078796e+01,
        -1.22808691e+01],
       [ 8.15324159e+02,  7.21538643e+01, -4.91068655e+00,
         2.15566517e+00],
       [-9.02469696e+01,  7.86144251e+01,  3.41674300e+00,
        -3.32048198e-01],
       [ 8.85999273e+02,  9.18335748e+01, -2.71070141e+01,
        -9.83255887e-01],
       [-3.91368534e+02,  3.83376414e+00, -3.40917150e+00,
         3.28739613e+00],
       [ 2.84948132e+02, -6.23920145e+01, -7.94870246e+00,
        -1.87436082e+00],
       [ 3.32775688e+02, -2.02190265e+01, -1.59573900e+01,
        -6.80821586e+00],
       [ 9.11666092e+01,  6.96907059e+01, -1.81282313e+01,
         4.46593214e+00],
       [ 8.26132127e+02, -8.92460368e+00, -1.77419646e+01,
         1.71547674e+00],
       [-2.72443965e+02, -9.51646012e+00, -5.33841354e+00,
        -4.14092918e+00],
       [-4.06046033e+02, -2.46173487e+01,  1.69790412e+01,
        -4.24621112e-01],
       [-4.92118676e+02, -1.08946723e+00,  2.11462857e-01,
         4.81843818e+00],
       [ 9.36953428e+01, -2.65917254e+01,  5.54387806e+01,
        -1.04084468e+01],
       [-5.23163457e+02,  8.73332816e-01,  1.58279460e+01,
         8.13465070e+00],
       [-6.52274806e+02, -3.46387045e+01,  9.99652340e+00,
         1.43898099e+01],
       [ 3.85449591e+02, -4.73833262e+01,  1.22140250e+01,
        -2.07689287e+00],
       [-4.57449129e+02, -2.38970894e+01,  6.85197564e+00,
         7.70383290e-02],
       [-2.77648999e+02,  8.76978343e-01, -8.52383380e+00,
         5.86898303e-01],
       [-5.32841585e+02, -2.84347570e+01,  7.92169110e+00,
         5.61418921e+00],
       [-4.33332099e+02,  2.76974958e+00,  8.95391099e+00,
         3.92014578e+00],
       [-3.63460535e+02, -4.06684587e+01,  4.49452095e+00,
        -3.03800142e+00],
       [-4.23585520e+01,  6.66974241e+01,  5.39662749e-01,
        -2.87909513e+00],
       [-1.05468675e+02,  4.65610098e+01, -1.41591572e+01,
         1.21044861e-01],
       [-1.69629355e+02,  2.05230771e+01, -9.37688570e+00,
         3.54878585e+00],
       [-2.96311445e+02,  2.11761856e+01,  1.08640803e+01,
        -7.75250915e-01],
       [-7.76088604e+02, -5.90733781e+01,  1.48420456e+01,
         4.38428385e+00],
       [-6.11750001e+02, -4.38521265e+01,  4.47610072e+01,
         4.25540924e+00],
       [-5.19561601e+02, -5.35418241e+00,  5.03892846e+00,
         1.01393246e+01],
       [-2.34884741e+02,  6.37529002e+00, -4.61060090e+00,
         2.35142374e+00],
       [-3.73013711e+02, -2.35977308e+00, -2.81305642e+00,
         1.82698703e+00],
       [ 5.23876767e+02,  4.60537487e+01,  2.36974925e+01,
        -3.16636416e+00],
       [ 2.47070962e+02,  1.14295916e+02, -8.51562849e+00,
        -1.61429826e+00],
       [-4.06209055e+02,  3.98322226e+00, -3.90335007e+00,
         8.26623462e+00],
       [-5.02293565e+02, -3.35343242e+01,  7.28544644e+00,
         8.84992624e+00],
       [-4.09978422e+02, -2.63022843e+01,  2.07523403e+01,
        -5.06230372e+00],
       [ 7.90621392e+02,  1.11272011e+02,  3.42339597e+01,
         2.77624189e+00],
       [ 1.44842836e+03, -2.23240781e+02, -2.17327813e+01,
         9.87848601e+00],
       [-3.79990840e+02,  7.11926174e+00,  2.20562636e+00,
        -3.45111083e+00],
       [ 1.83936889e+03,  9.12888973e+01, -4.33997887e+01,
         1.91943295e+01],
       [-6.71063180e+01,  8.13124937e+01, -2.04584617e+01,
         1.96468661e+00],
       [-5.55406210e+02, -1.22228727e+01,  3.34995905e+00,
         1.45698051e+01],
       [ 4.46202676e+02,  1.22499207e+00,  1.91005245e+00,
        -8.11598488e-01],
       [ 8.42414450e+02, -1.22192197e+02,  3.49654967e+01,
        -1.14596054e+01],
       [-5.88924817e+01,  7.17685998e+01, -1.33602005e+01,
         2.19920357e+00],
       [-3.83867453e+02,  8.91186935e+00, -1.14565022e+00,
         8.06649530e+00],
       [ 5.04877075e+01, -1.35395528e+02,  5.22459385e-01,
        -6.15595408e+00],
       [ 2.32515164e+02, -4.43849974e+01, -8.86739506e+00,
         3.25332766e+00],
       [-5.62095002e+02,  9.80852549e+00,  1.10290991e+01,
         9.88635758e+00],
       [-5.63845042e+02, -1.61867354e+01,  1.41262935e+01,
         7.75154756e+00],
       [-7.55967624e+02, -4.38410942e+01,  1.52864778e+01,
         1.41250527e+01],
       [-6.03444135e+02, -4.72085163e+01,  2.16966637e+01,
         1.77791858e+00],
       [ 1.78688536e+02,  1.00339218e+02, -2.04871615e+01,
        -6.68936364e+00],
       [-3.00734139e+02,  3.09274552e+01, -9.15184816e+00,
         4.55301476e-01],
       [-3.42038877e+02,  3.59439162e+01,  9.04538541e-01,
         9.04317650e+00],
       [ 2.82824144e+03,  1.51248568e+02, -6.62930353e+01,
         3.25340783e+01],
       [ 1.37639231e+03, -6.57598025e+01, -3.55956407e+01,
        -2.19075595e+00],
       [ 3.90199157e+02, -1.06224105e+02, -2.07794957e+01,
        -2.84954783e+00],
       [-4.86023943e+02, -1.75371131e+00,  1.01619309e+01,
         6.93055170e+00],
       [ 1.07058280e+02, -3.82196566e-01, -2.71023046e+01,
        -1.19375395e+00],
       [-5.55748840e+02, -5.86793616e+01,  1.83242799e+01,
         5.84156808e+00],
       [ 6.52582105e+02,  5.53452680e+01, -4.79477714e+01,
         6.34110193e+00],
       [-4.30248093e+02, -1.44061830e+01,  1.92848321e+00,
         3.48876301e+00],
       [-4.53465837e+02,  9.49686433e+00, -1.86055503e-01,
         3.17615364e+00],
       [-3.86067386e+02,  9.76166538e+00, -2.70363398e-01,
         4.67864456e+00],
       [-1.24350866e+02,  2.30255898e+01, -3.13319839e+00,
        -1.32840390e+01],
       [-3.33298359e+02,  3.03436350e+01,  3.17460396e+01,
        -2.92347433e+00],
       [-6.85469642e+02, -1.47222421e+01,  2.11458262e+01,
         8.89669814e+00],
       [-1.87830802e+02, -9.40838009e+01,  4.33754541e+00,
        -1.35098824e+01],
       [-7.31331619e+01,  6.42803758e+01, -1.33991589e+01,
        -1.44689984e+01],
       [-3.12697321e+02,  2.68228855e+01, -7.15671012e+00,
         3.60696487e+00],
       [-9.61624219e+01, -1.80495611e+01,  1.35216945e+01,
        -1.45892003e+01],
       [ 4.90818029e+02,  1.35753937e+02,  7.85376430e+00,
         5.86498280e-01],
       [ 9.47873219e+02,  2.66754680e+00, -4.01129638e+01,
        -7.09434376e+00],
       [ 1.32419751e+02, -9.53795705e+01, -2.82106593e+01,
        -2.74062299e+00],
       [-3.08525888e+02, -4.02779118e+01,  4.26041604e+00,
        -2.54290949e+00],
       [ 4.61217812e+02,  6.79364351e+01, -2.67187831e+01,
        -4.04185901e+00],
       [ 1.48260886e+03,  3.07417114e+02, -4.14645447e+01,
         3.10576223e+00],
       [ 2.04418599e+02, -1.90383277e+02,  6.82744265e-01,
        -1.76078593e+01],
       [-2.63623436e+02, -4.27685526e+01,  4.72069976e+00,
        -1.62110219e+00],
       [ 1.24670054e+02, -3.63417922e+00, -2.11100852e+01,
         2.69749257e+00],
       [-6.58207460e+02, -2.29160762e+01,  9.84491692e+00,
         6.40414367e+00],
       [ 4.12942923e+02,  4.25929797e+01,  4.54576214e+00,
        -1.64919268e+00],
       [-2.72412738e+02,  1.79465807e+01, -1.10952783e+01,
        -7.75859392e+00],
       [ 8.02698919e+01,  3.34517733e+01, -2.49446908e+01,
         8.12286455e+00],
       [ 9.97051472e+02,  1.41215970e+02,  1.46007151e+01,
        -3.36371249e+00],
       [-4.05092970e+02, -2.07421812e+01, -2.70960286e-01,
         1.42642752e+00],
       [ 2.36670071e+03,  7.39620918e+02,  3.51768090e+02,
         2.00359001e+00],
       [ 2.73638271e+02,  1.78227005e+02,  1.34985349e+00,
        -4.88820707e+00],
       [-8.19335858e+01, -1.78031024e+00, -6.36323312e+00,
        -1.56328756e+01],
       [-1.51621888e+02,  2.88015225e+00, -9.94384395e+00,
        -3.75349320e+00],
       [-4.15428109e+02, -9.19541221e+00,  4.25321130e+00,
        -1.66575202e+00],
       [-5.82354150e+02, -3.82153073e+01,  1.57247053e+01,
         1.99312681e+00],
       [ 1.26795997e+03, -9.36012127e+01,  1.41458693e+01,
        -1.10054972e-02],
       [ 1.66281535e+03, -3.43279037e+02, -1.99173950e+01,
         2.09604286e-01],
       [-1.94876522e+02,  1.70948549e+01, -1.21852150e+01,
         6.01617324e+00],
       [-2.15206500e+02,  2.08669307e+01, -7.78198358e+00,
         2.72600166e+00],
       [-6.11093115e+02, -3.05431695e+01,  9.70806501e+00,
         4.61617388e+00],
       [ 2.32615719e+02, -1.66088239e+01, -2.19264019e+01,
        -5.93690584e+00],
       [-2.04015093e+02, -3.68624871e+00, -4.34522065e+00,
         8.18948028e-01],
       [-1.27813836e+01, -7.59519970e+00,  8.56008365e+00,
         2.88715158e+00],
       [-5.85755132e+02, -2.66611850e+01,  5.14084317e+00,
         7.24269481e+00],
       [-4.69995973e+01,  6.31351095e+01, -1.90905344e+01,
        -1.15753251e+00],
       [-3.02943962e+02, -2.57684419e+00, -5.03309069e+00,
        -3.90498921e+00],
       [-2.28327736e+02, -3.90889659e+01, -3.45772720e+00,
        -1.10688112e+01],
       [ 3.88504338e+02,  4.55473651e+01, -3.11552035e+01,
        -2.04061285e+00],
       [-5.02721083e+02,  1.57794146e-01, -3.65861494e+00,
        -5.37196244e+00],
       [-4.91150894e+02, -1.72257242e+01,  2.56847035e+00,
        -1.13039377e+01],
       [ 1.19401173e+03,  5.31752125e+01, -3.68712501e+01,
         4.40698874e-01],
       [-6.62870513e+02, -3.87230175e+01,  1.08641860e+01,
         1.04280356e+01],
       [-1.68802906e+02,  4.16011382e+01, -9.36887543e+00,
        -2.93936320e+00],
       [ 2.29647999e+03, -2.03099281e+02, -9.10975694e+00,
         1.31116118e+01],
       [ 1.08392975e+03,  1.05659762e+02, -1.76660411e+01,
         3.44558454e+00],
       [-1.16086235e+02,  3.39351907e+01, -4.97283276e+00,
        -1.28160315e+01],
       [ 5.89796832e+02, -4.66624331e+01, -2.51060979e+01,
        -1.78017929e+01],
       [-2.10733365e+02,  3.43979297e+01, -1.28415253e+00,
         5.93336810e+00],
       [-3.82931152e+02,  2.22895021e+01, -9.50728293e+00,
         7.89111792e+00],
       [-4.87582338e+02, -1.56193262e+01,  2.87680216e+00,
        -4.98947899e+00],
       [-1.82892462e+02,  3.52231815e+01,  9.34465028e+00,
        -3.86323083e+00],
       [ 7.19906380e+02,  1.49652208e+02, -2.15731144e+01,
        -3.60896762e+00],
       [-5.74574508e+02, -2.36542436e+01,  1.55831152e+01,
        -4.18331250e-01],
       [-2.98650717e+02,  4.75679296e+01, -1.01826389e+01,
         2.48584926e+00],
       [-2.81255737e+02,  3.45197888e+00, -9.26468423e+00,
        -2.32814980e+00],
       [-5.24769159e+02, -4.32871988e+01,  5.95712441e+00,
        -5.64767137e+00],
       [-4.62960334e+02, -1.09322037e+01,  4.65207263e+00,
         5.28713939e+00],
       [ 1.33889845e+03,  2.07293504e+01,  2.35592562e+01,
         4.38052516e+00],
       [-4.47248939e+02, -1.88838818e+01,  1.20492389e+01,
         1.81328268e+00],
       [ 1.18853270e+03, -7.46744344e+01, -1.25738520e+01,
         8.42361727e+00],
       [ 4.33729775e+02,  5.66696478e+01, -3.14737662e+01,
         2.83428144e+00],
       [ 1.20143758e+03, -1.26877957e+02, -3.46592349e+01,
         1.06263532e+01],
       [-7.38862448e+01, -1.63587289e+01, -8.68353897e-01,
        -1.30992035e+00],
       [ 1.18493051e+03, -7.00696079e+01, -1.06344260e+00,
        -1.58533224e+01],
       [ 7.33575437e+01,  2.55982300e+01,  1.35720586e+01,
        -7.66438378e+00],
       [ 3.63607158e+02, -7.66893692e+01,  7.56882969e+01,
        -2.75712168e+01],
       [ 1.78606495e+02, -3.32669898e+00, -2.92673832e+01,
        -2.35106204e+01],
       [ 1.15307437e+03,  4.10705259e+01, -5.23590514e+01,
         8.13158457e-02],
       [ 4.33284771e+02,  6.27779869e+01, -2.06050758e+01,
        -1.42072684e+00],
       [ 5.09679673e+02,  3.59013360e+01,  2.11869723e+01,
        -7.78093193e+00],
       [ 1.45369683e+02,  3.25006510e+01, -2.67872728e+01,
        -1.63763600e+00],
       [ 6.17242967e+02, -5.45430816e+01, -2.91653446e+01,
        -2.47678706e-01],
       [ 2.58482814e+03, -6.71532263e+02,  2.23224934e+01,
         9.78528442e+00],
       [-5.50815536e+02, -2.73989111e+01,  1.79447405e+01,
         2.90133273e-01],
       [-2.36592219e+02,  3.34187788e+01, -1.11288041e+00,
        -6.00243285e+00],
       [-3.17447230e+02,  2.48444211e+01, -4.34537379e+00,
         3.28770348e+00],
       [-5.64288141e+02, -2.12598920e+01,  1.22716451e+01,
        -2.62293205e-01],
       [-1.80884386e+02,  8.26240403e+01, -1.95476234e+01,
         7.45539484e+00],
       [-5.02158572e+02, -8.76765753e+00,  1.62441342e+00,
         9.53986581e+00],
       [ 1.72609476e+03, -6.48092733e+01,  2.06424945e+01,
        -1.24695568e+00],
       [-6.40723401e+02, -3.98914952e+01,  1.31908591e+01,
         8.30217772e+00],
       [ 5.54793060e+02,  6.60453444e+01, -2.61280847e+01,
        -3.35957031e+00],
       [-4.62647856e+02,  2.45107156e+01,  3.46528921e+01,
         2.95794686e+00],
       [-4.97118080e+02, -1.73913692e+00,  5.28958578e+00,
         8.28595145e+00],
       [ 5.35852305e+02,  1.97975875e+02, -3.41896612e+01,
         7.88952932e+00],
       [-1.64873302e+02,  2.68254509e+00, -8.93046513e+00,
         9.90208292e-01],
       [-2.16054890e+02,  5.16788181e+01, -9.40053291e+00,
         1.99440510e+00],
       [ 9.73891551e+02, -2.45884667e+01, -2.53980068e+01,
        -6.45422749e+00],
       [-4.15133649e+02, -1.46095423e+01,  2.12400199e+01,
         4.87522484e+00],
       [ 8.94419140e+02,  3.13309608e+01, -3.73213540e+01,
         3.42875238e+00],
       [ 2.06700123e+02,  5.07627208e+01, -2.53113505e+01,
        -5.32225356e+00],
       [-3.16321408e+02,  2.97785960e+01,  3.86451328e-01,
         2.69134825e+00],
       [-3.57935747e+02,  2.23127016e+01,  2.33175008e+00,
         3.49953597e+00],
       [-3.97834640e+02, -9.41485246e+00,  3.30002304e+00,
        -5.99696425e+00],
       [-3.33456289e+02,  3.86944633e+01, -8.68523926e+00,
         1.01822634e+01],
       [-5.14676563e+02,  6.92702810e+00,  2.32851540e+01,
         3.93440644e-01],
       [-4.96155389e+02, -3.00670820e+00,  5.20970046e+00,
         1.22857176e+00],
       [-9.66263442e+01,  5.61472080e+01,  4.13845386e+01,
        -4.22832881e+00],
       [-4.41507077e+01,  6.45992653e+01, -1.40274627e+01,
        -2.97684539e+00],
       [-3.27023019e+02,  3.25045174e+01, -4.38501483e+00,
         5.10469506e+00],
       [-4.27173310e+02, -1.95383949e+00, -2.42965253e+00,
         1.54852357e+00],
       [-3.65512135e+02,  3.05004076e+01, -6.55937084e+00,
         6.25186945e+00],
       [-2.26423133e+02,  5.22990104e+01, -9.96598525e+00,
         8.08777676e+00],
       [-5.70885077e+02,  4.28105681e+00,  3.64599918e+00,
         1.22262344e+01],
       [-3.95512449e+02, -2.16620018e+01,  3.12653588e+01,
        -1.88360981e-01],
       [-6.43442992e+01,  1.28966523e+01, -1.64317674e+01,
         7.24797775e-01],
       [-6.10885098e+02, -5.74524668e+00,  1.50779287e+01,
         2.25396463e+00],
       [ 1.29923246e+03, -1.27454388e+02,  2.13613319e+01,
         2.05791749e+00],
       [-3.77510342e+02,  1.39646535e+01,  8.89020171e+00,
        -7.72815117e-01],
       [ 1.01001071e+03,  8.39111359e+01,  3.30698875e+01,
        -7.33241557e+00],
       [-6.00574132e+02, -1.23314728e+01,  4.09968681e+00,
         4.87123956e+00],
       [-4.65988360e+02, -1.26188547e+01,  8.94263293e+00,
         2.09184264e+00],
       [-4.70296059e+02,  6.16013205e+00,  4.10002591e+00,
        -4.43028099e+00],
       [-2.70868078e+02,  2.58779137e+01, -9.60907396e+00,
         5.56972159e+00],
       [-7.23567560e+02, -4.11681757e+01,  1.16744676e+01,
         1.20653957e+01],
       [-2.02784223e+02,  1.85714074e+01, -8.30775122e+00,
         8.71990703e+00],
       [-2.43066638e+02,  1.81132041e+00,  6.60609864e+00,
         6.31965461e+00],
       [-4.64330683e+02,  4.04439570e+00, -2.87740077e+00,
         1.60703505e+00],
       [-2.95306512e+01,  2.92297527e+01, -9.66704520e+00,
         5.62226021e+00],
       [-3.02989062e+02,  7.02324385e+00,  1.94157389e+00,
         6.18103000e+00],
       [-4.82500226e+02,  3.97064839e+00, -3.33363163e+00,
         1.13163031e+01],
       [-7.75054946e+02, -3.90794127e+01,  2.26300611e+01,
         9.24472416e+00],
       [-3.79352925e+02,  2.62863129e+01, -6.11298331e+00,
         6.81261726e+00],
       [-4.16348258e+02,  2.51942427e+01, -6.74425501e-01,
         9.83445758e+00],
       [ 7.10453791e+02,  4.61169902e+00, -3.08178779e+01,
         6.05569272e+00],
       [-7.13269922e+02, -4.84454609e+01,  2.45407906e+01,
         9.89273355e-01],
       [-4.04813013e+02,  3.74287380e+01,  1.37674347e+01,
         5.26800613e+00],
       [-5.92300476e+02, -2.86009197e+01,  1.63861937e+01,
         6.34379683e+00],
       [ 9.87023111e+02,  1.26629989e+02, -2.04466319e+01,
         1.01007058e+01],
       [-3.19483750e+02,  1.75578394e+01, -6.12983982e+00,
         3.17240493e+00],
       [ 1.22221252e+03, -2.78035856e+01, -3.95427542e+01,
         4.94861918e-02],
       [-3.57812660e+02, -1.41672551e+01, -1.25467577e+00,
         2.33235376e+00],
       [-3.48765803e+02,  1.78079155e+01, -3.22748773e+00,
         3.33725317e+00],
       [-1.32657995e+02,  3.50966340e+01, -8.85501762e+00,
         8.24664753e+00],
       [-4.15424310e+02,  6.56958356e+00,  2.61781027e-01,
         4.58618640e+00],
       [ 2.88844429e+02,  1.12396008e+01, -1.32131305e+01,
        -8.12748340e+00],
       [ 1.71325412e+02,  9.83831393e+01,  6.94622517e+00,
        -1.59714397e+00],
       [ 2.33819327e+02,  2.02557075e+01, -2.08037353e+01,
         7.71533002e-01],
       [-2.84451886e+02,  7.41619394e+00, -4.46687209e+00,
        -3.08587794e+00],
       [-5.20429177e+02,  1.64324958e+00,  8.72337005e+00,
         1.30470150e+00],
       [-4.70842227e+02, -2.54815613e+01,  1.59159533e+00,
         4.65871241e+00],
       [-3.88138950e+02,  1.13816187e+01, -5.27907161e+00,
         9.29944039e-01],
       [ 5.51656022e+02, -2.40643080e+01,  1.51450827e+01,
        -1.14598321e+01],
       [-3.34955591e+02,  3.79811419e+01, -7.10363074e+00,
         8.04575163e+00],
       [ 1.07804794e+03, -1.41250339e+02, -1.13596857e+01,
        -1.51595229e+00],
       [-6.05035298e+02, -3.69529138e+01,  1.11582105e+01,
         2.68623393e+00],
       [ 2.30421759e+03, -1.17535109e+02, -1.22356797e+00,
         1.87818252e+01],
       [-2.30141426e+01, -1.91459218e+00, -7.41941712e+00,
        -6.59988245e-01],
       [-6.47016431e+02, -4.71254257e+01,  8.84353606e+00,
         4.56971248e+00],
       [-5.24429248e+02, -1.18037787e+01,  1.63790920e-01,
         5.09951814e+00],
       [ 8.45947142e+02,  1.19000997e+02, -2.16337074e+01,
        -8.50174989e+00],
       [-4.34234474e+02, -1.16352281e+01,  8.87240264e+00,
         5.01728451e+00],
       [-6.22255336e+02, -1.35328158e+01,  1.46252231e+01,
         6.93321658e+00],
       [-3.82097430e+02, -1.44239295e+01, -7.73463230e-01,
         2.42904621e-01],
       [ 7.11501655e+00,  1.18680326e+01, -1.21792584e+01,
         1.92195205e+00],
       [-4.78899996e+02, -5.78267527e+00, -7.73519256e-01,
         6.12778808e+00],
       [-4.47998868e+02,  4.47918121e+00,  1.15528919e+01,
         4.67055978e+00],
       [-4.11614689e+02, -2.47025518e+01,  9.38920529e+00,
         5.26282096e+00],
       [ 8.49318901e+01,  7.13634537e+01,  4.35240915e+00,
        -8.07673840e+00],
       [ 2.72100090e+03, -6.27362935e+01, -3.59656327e+01,
         2.48314219e+01],
       [ 1.78493416e+02, -3.50470250e+01,  1.24416573e+01,
        -1.13010288e+01],
       [-5.06414893e+02, -9.52717232e+00,  1.74479880e+01,
         6.80319476e+00],
       [-3.73291881e+02,  2.84426679e+01,  7.68425484e+00,
        -7.47643425e-01],
       [-3.22378849e+02,  2.81221621e+01, -1.45779934e+00,
        -3.10075980e+00],
       [-1.92016715e+02,  4.42909144e+01, -9.16553863e+00,
         1.82813662e+00],
       [-7.10878225e+02, -5.40530217e+01,  3.11388245e+01,
         8.09665643e+00],
       [-5.73512756e+02, -9.34491186e+01,  2.34532143e+01,
         1.76423166e+00],
       [-3.37662831e+02,  1.36031088e+01,  7.19767946e+00,
         4.37390283e+00],
       [-2.79264179e+02,  4.15181484e+01, -4.24936076e+00,
        -3.14548799e+00],
       [-3.40809359e+02,  2.07287599e+01, -4.09761201e+00,
         1.00370384e+00],
       [ 2.04757006e+02,  9.02117254e+01, -1.88834693e+01,
         1.75626254e+00],
       [-2.40380402e+02,  2.49680742e+01, -1.36589627e+01,
         4.68254546e+00],
       [ 1.10217709e+03,  7.89875905e+01, -2.95333915e+01,
         4.95052172e+00],
       [ 9.80521469e+02,  8.54975242e+01,  7.24612069e+00,
        -9.96455327e+00],
       [-3.22054014e+02, -3.53392209e+01, -3.72487051e+00,
        -4.11193118e-01],
       [ 2.40494229e+03, -4.12309143e+02,  5.60237066e+01,
         2.54023155e+01],
       [ 1.58612829e+03,  8.94825895e+00,  8.28452749e-01,
        -3.27612342e+00],
       [ 3.40252376e+02,  1.12388959e+01, -1.47672611e+01,
        -7.12193689e+00],
       [-2.42145805e+01,  8.07779530e+01, -2.14516352e+01,
         9.79796726e+00],
       [ 9.39399721e+02,  2.85852964e+02, -5.51258179e+01,
         1.11445421e+01],
       [ 1.26588250e+03,  2.86391560e+01, -3.31809479e+01,
         1.17865584e+01],
       [-2.20141640e+02,  4.41996131e+01, -1.45167397e+01,
         2.64747742e+00],
       [ 5.21529369e+01,  1.24551170e+02, -2.96037040e+01,
         3.19749667e+00],
       [-6.18289177e+02,  3.49350017e+00,  1.42301218e+00,
        -2.18644696e-01],
       [-2.20454409e+02,  2.41655145e+01, -1.37586568e+01,
        -8.47394158e+00],
       [-2.31153056e+02,  5.25629630e+01, -1.65512104e+01,
         3.78027542e+00],
       [-4.71867248e+02, -5.77227613e+01, -6.85792098e-01,
        -1.01956339e+01],
       [-4.86648595e+02, -1.98613949e+01,  2.98786130e+00,
         2.74808804e+00],
       [-5.18977293e+02, -1.65734276e+01,  8.17680696e-01,
         5.02505267e+00],
       [-4.44380417e+02,  2.63057937e+01, -6.58885726e+00,
        -5.14059515e+00],
       [-3.40081211e+02, -1.88140420e+01, -2.53056579e+00,
        -2.24716918e+00],
       [-2.79529558e+02,  3.67248079e+01, -9.87170784e+00,
         4.04766708e+00],
       [-9.97697592e+01,  7.19499384e+01, -2.60282660e+00,
        -5.61165772e+00],
       [-4.01127519e+02,  1.70629831e+01,  2.01630296e+00,
         3.95447742e+00],
       [-1.46890514e+02,  2.03880890e+01, -8.98474990e+00,
         4.82660636e+00],
       [-5.05808135e+02, -1.35896907e+00,  1.12628019e+01,
         4.60445962e+00],
       [ 6.41497926e+02,  2.19956200e+02, -8.05467237e+00,
        -5.77118825e+00],
       [-5.90719281e+02, -3.29998509e+01,  5.66342336e+00,
         1.07752148e+01],
       [-7.01731349e+02, -6.77317009e+01,  2.94266959e+01,
         6.65035473e+00],
       [ 4.57687259e+02, -1.71342840e+02,  8.99632903e-01,
        -1.00095242e+01],
       [ 1.41897688e+03,  2.03571789e+01, -3.79635596e+01,
         7.91685500e+00],
       [-3.83907762e+02, -1.19055350e+01,  3.28090169e+00,
        -8.42931366e-01],
       [-1.92915575e+02,  6.25730186e+01, -1.72743356e+01,
         2.48370561e+00],
       [-2.26835333e+02,  2.38751029e+01, -8.94729497e+00,
        -2.23831581e+00],
       [-3.24223054e+02,  2.50659148e+01,  8.17398596e+00,
         1.33761687e+00],
       [-4.73757538e+02, -3.76742917e+01, -6.71532846e-02,
         6.71154968e+00],
       [-3.89230260e+02, -2.55244955e+01,  6.87273764e+00,
         1.76775186e+00],
       [ 5.39399089e+02,  7.08305834e+01, -3.13655458e+01,
        -1.14423995e+01],
       [-3.60470743e+02, -3.05323942e+01, -6.30535447e-01,
         7.16391529e+00],
       [-2.89405492e+02,  2.33454715e+01, -4.50615495e+00,
        -2.08318780e+00],
       [-3.34306607e+02,  2.95606299e+01, -1.04803479e+01,
         3.00647648e+00],
       [-3.94359342e+02,  2.15256810e+01,  1.22377577e+01,
         6.82244855e+00],
       [-4.97861513e+02, -3.20077975e+01,  1.35063588e+01,
        -1.48658211e+00],
       [ 1.32173362e+02,  8.93647206e+01, -2.65835714e+01,
         5.21988923e+00],
       [-2.73669212e+02,  1.82922419e+00,  1.61340092e+01,
        -2.54184333e+00],
       [ 5.76209588e+02,  4.51663962e+01, -2.32465784e+01,
         6.12659342e-01],
       [-3.30164205e+02, -2.12969526e+01,  4.08267781e+00,
        -8.10483059e-01],
       [-4.41247952e+02, -3.21354434e+01, -2.03585841e+00,
        -4.83152973e+00],
       [-4.97867645e+02, -2.88272353e+01,  1.46491508e+00,
         1.82202175e+00],
       [-6.98452816e+02, -2.99911051e+01,  6.40432254e+00,
         1.97039902e+00],
       [ 8.28217694e+00,  4.02489070e+01, -1.31797734e+01,
        -5.81910700e+00],
       [ 7.73496363e+01,  2.87905790e+01,  1.53468538e-01,
        -9.46389738e+00],
       [-4.21863664e+02, -3.60094538e+00,  2.76553454e+00,
        -1.73116926e+00],
       [-6.46308854e+02, -5.82130621e+01,  2.20106391e+01,
        -8.49036001e-01],
       [ 8.26211142e+02, -3.22901516e+02,  9.13058450e+01,
        -1.37755258e+01],
       [-3.52599928e+02,  2.60955569e+01, -3.07099851e+00,
         7.91667258e+00],
       [-5.05324890e+02, -1.58159931e+01,  7.17213874e+00,
        -1.57842445e+00],
       [-4.36338009e+02, -2.30079105e+01,  4.36590109e+00,
        -2.13920747e+00],
       [-5.91573734e+01,  3.87107443e+01,  1.10601068e+01,
        -4.50281786e+00],
       [-4.75742905e+02, -8.49174313e-01,  2.35504040e+00,
         4.22533286e+00],
       [-1.89064489e+02,  2.11712758e+01, -1.10970557e+01,
        -2.62392073e+00],
       [-6.17194385e+02, -5.32272111e+01,  3.87076059e+01,
         1.24272495e+00],
       [-6.13829443e+02, -3.60872727e+01,  6.51778372e+00,
         2.11444451e+00],
       [-5.44413156e+02, -4.65431552e+01,  1.12862525e+01,
         1.75182691e+00],
       [-4.88804882e+02, -4.97386372e+01,  7.35440816e+00,
        -5.45261709e+00],
       [-5.37173976e+02,  4.07192686e+00,  1.57425207e-01,
         7.92585717e+00],
       [-3.31993064e+02,  2.11008470e+01,  1.56944384e+00,
         3.57752100e+00],
       [-2.48657913e+01,  5.10200527e+01, -1.74160191e+01,
        -1.67210661e+01],
       [-4.10186841e+02,  2.94103702e+01, -2.57795592e+00,
        -1.36749787e+00],
       [ 8.21589728e+02,  1.98676102e+02, -3.48109743e+01,
         5.47743715e+00],
       [ 8.57390181e+02,  1.46293468e+01,  1.57957810e+01,
        -8.27950412e-01],
       [-7.91889284e+01,  6.97414169e+01, -1.23714623e+01,
         4.45287521e+00],
       [-3.91209726e+01, -4.16049671e+01, -2.00731037e+01,
        -7.44899894e+00],
       [-2.93170335e+02,  7.06871075e+00,  2.19024792e+00,
        -2.22579580e+00],
       [-1.34669890e+02,  3.05239150e+01, -3.03354545e-01,
         2.23265630e+00],
       [-1.45250730e+02,  1.49582652e+01, -2.95529905e+00,
        -2.44234478e+00],
       [-1.90164936e+02,  5.81944308e+01, -1.06469669e+01,
         5.68685509e+00],
       [-4.93690843e+02, -3.27967913e+01,  4.92994307e+00,
        -6.03837036e+00],
       [ 4.88376228e+02,  2.49440661e+01, -9.88616599e+00,
        -7.08448484e+00],
       [-1.85145247e+02,  3.14679694e+01, -7.34688180e-01,
         4.91278233e+00],
       [-6.04822971e+02, -1.94074215e+00,  7.47527597e+00,
         6.16504041e+00],
       [ 5.25706888e+02,  7.32757614e+01, -3.43075768e+01,
         6.39163283e+00],
       [-4.25633512e+02,  7.48960871e+00,  2.61436636e+00,
        -4.81693857e+00],
       [ 6.46046225e+02, -9.44846486e+00, -3.33384559e+01,
        -1.02857881e+01],
       [-3.43241415e+01,  4.36500170e+01, -1.90610399e+01,
         2.75826397e+00],
       [-4.10213185e+01,  3.01084656e+01, -1.56640019e+01,
        -2.76292933e+00],
       [ 1.35645994e+03,  3.09994245e+01, -3.33674065e+01,
         8.10173225e+00],
       [-4.36192585e+02,  3.04513954e+00,  4.22474038e+00,
        -2.23045919e+00],
       [ 7.41384890e+02,  1.78111065e+02, -2.64264886e+01,
         1.55476540e+00],
       [-4.16941153e+02,  3.21488603e+00, -3.54765103e+00,
        -9.23001786e+00],
       [-1.17871335e+02,  5.89600115e+01, -8.53244289e+00,
         4.88865434e+00],
       [-2.96968964e+02, -1.04404480e+01, -1.01707028e+01,
         3.91999407e+00],
       [-2.00880953e+02,  7.04543060e+00, -8.79580577e-01,
        -1.32288263e+01],
       [-4.27105870e+02, -2.23238645e+01,  6.28261926e+00,
        -1.20451724e+01],
       [-2.73821557e+02,  2.82768118e+01, -7.82953981e+00,
        -5.21851313e+00],
       [-2.86588766e+02,  1.54497730e+01, -3.36764949e+00,
        -4.49918517e+00],
       [-6.44928887e+02, -3.65603367e+01,  7.69824294e+00,
        -4.57415988e+00],
       [ 8.03716112e+02, -1.62098690e+02,  3.04161334e+01,
        -1.15363810e+01],
       [ 3.86717805e+03, -1.71017440e+02,  2.92751670e+02,
         1.70234253e+01],
       [-1.30334367e+02,  6.81534783e+01, -1.33158080e+01,
        -5.59738955e+00],
       [-4.57054159e+02, -7.28545535e+00, -1.63011134e+00,
         2.28613704e+00],
       [-2.27411027e+02, -5.02889106e-01, -1.06563565e+01,
         2.48631662e+00],
       [-1.83928135e+02, -1.94028890e+01, -7.76549057e+00,
        -1.20620011e+01],
       [-2.25395498e+02, -1.46610467e+00, -9.69370290e-01,
        -4.78921339e+00],
       [-6.20872171e+02, -5.60022768e+01,  1.64903737e+01,
         3.83750454e+00],
       [ 6.48811118e+02, -9.67822499e+00,  2.75623528e+01,
        -9.11354273e+00],
       [-4.29748209e+02, -2.75070144e+01,  1.13431323e+01,
        -3.41015943e+00],
       [-6.15058977e+02, -5.61898238e+01,  1.79184383e+01,
         3.27525781e+00],
       [-3.73872299e+02, -1.29971580e+01,  2.53679204e+01,
        -9.56447276e+00],
       [ 3.81305542e+01,  1.40147964e+01, -1.93480279e+01,
         4.97982199e+00],
       [-3.73893334e+02,  4.62415716e+00,  1.54931178e+01,
        -1.02160879e+01],
       [-5.38116442e+02, -2.10684163e+01, -3.43848587e-01,
         4.10927541e+00],
       [-3.13282620e+02,  1.60546101e+01, -1.13454206e+01,
         3.79257542e+00],
       [-6.34926725e+01, -4.07985883e+00, -6.71700995e+00,
        -7.18898653e+00],
       [-1.68343867e+02,  3.64380669e+01, -1.72813561e+01,
         2.49549442e+00],
       [-4.84481541e+02,  4.19557084e-01,  1.26788987e+00,
         3.67388576e+00],
       [ 1.34503261e+02,  1.07457218e+02, -1.65629526e+01,
        -5.20560663e+00],
       [-3.89808953e+02,  2.07600547e+00, -2.53723493e+00,
        -1.95417947e+00],
       [-7.04629661e+01, -1.85600966e+01, -7.95517585e+00,
        -1.35108107e-01],
       [-2.46258593e+02,  2.16530732e+01, -1.38510526e+01,
         5.82663190e+00],
       [-2.10513421e+02,  2.91185608e+01, -8.13081078e+00,
         2.15577626e+00],
       [ 2.44347066e+01,  9.29604187e+01, -2.87110224e+01,
         7.38552339e+00],
       [-3.49091838e+02,  3.53879589e+00,  8.56012251e+00,
        -4.65671464e+00],
       [-3.76290741e+01,  3.52365591e+01, -1.86129497e+01,
         1.75459915e+00],
       [ 1.00214850e+03, -7.99819997e+00, -2.81310262e+01,
         4.61949099e+00],
       [-4.05353203e+02, -2.88205494e+01,  1.02034379e+01,
         2.09589014e+00],
       [ 2.78679418e+02,  6.77714099e+01, -3.39678542e+01,
        -1.70255641e+00],
       [-3.19372507e+02, -2.76852621e+01, -4.58534111e+00,
        -5.21720050e+00],
       [ 4.57339406e+02,  1.17674604e+02, -1.51235465e+01,
         1.00741505e+01],
       [ 6.52244528e+02,  1.85094041e+01,  1.23853492e+01,
        -4.06994962e+00],
       [-3.89694528e+02,  2.80487250e+01,  6.52830890e+00,
         9.19034626e+00],
       [-2.59641710e+02,  2.11048877e+01, -1.60481949e-01,
        -3.33634698e+00],
       [-7.02344941e+01,  7.26516195e+01, -1.53695254e+01,
        -1.77888851e+00],
       [-3.00030110e+02, -1.65976589e+01, -5.41381150e+00,
        -4.13420279e-01],
       [-3.25928982e+02, -7.77853015e+00, -1.03356948e+01,
         5.66171749e-01],
       [ 8.32609773e+02, -1.96837890e+01,  9.40003693e+00,
         4.27169917e+00],
       [ 1.09948689e+03,  1.12597421e+02, -2.74760668e+01,
         1.45936570e-01],
       [-2.30675677e+00,  4.21731553e+01, -6.04885982e+00,
         8.95003541e-01],
       [-1.09464701e+02, -2.22926896e+00,  3.85434408e+00,
        -1.08715999e+01],
       [-3.74935084e+02,  1.78700716e+01, -9.06955997e-01,
         3.39686957e+00],
       [ 2.16618517e+03, -1.08422615e+02,  2.11706549e+01,
         9.87026484e+00],
       [-7.08652366e+02, -4.63099698e+01,  2.02560511e+01,
         6.97409478e+00],
       [-6.72591115e+02, -4.04102466e+01,  1.58040848e+01,
         7.11172242e+00],
       [-4.18653294e+02,  1.69758350e+01, -4.52805008e+00,
         4.95592309e-01],
       [-5.52979663e+02, -3.10695545e+00,  3.31206067e+00,
         4.84203677e+00],
       [ 1.25261547e+02,  1.16510102e+02, -2.69461099e+01,
         1.00252993e+01],
       [ 6.45965121e+01,  5.06508744e+01, -1.32051906e+01,
        -1.35190442e+01],
       [-4.68335643e+02,  1.53650468e+01, -8.27114796e-01,
         6.94622048e+00],
       [-9.05470582e+01,  8.47029371e+01, -1.48621907e+01,
         7.32050378e+00],
       [-8.17538714e+01, -6.51570081e+01, -2.87823954e+00,
        -1.01216936e+01],
       [-1.38829918e+01,  1.32422161e+01, -2.58296105e+00,
         4.77008327e+00],
       [ 9.83555360e+01, -4.57581581e+00, -7.63713424e+00,
        -2.02273350e+00],
       [-4.82149027e+02, -1.70433627e+01,  5.32053154e+00,
         3.43996974e+00],
       [ 7.31367197e+02,  2.20002561e+01, -1.38378621e+01,
         2.59339969e+00],
       [ 9.46295946e+02,  8.10505091e+01, -3.43397975e+01,
         7.44545458e-01],
       [-2.60052625e+02, -3.13150416e+01,  8.06810309e+00,
        -4.77076327e+00],
       [-3.03492556e+02, -4.54599550e+00,  5.07992238e+00,
         3.64805305e-01],
       [-6.81583641e+02, -5.24010634e+01,  1.86947015e+01,
         8.55897611e+00],
       [ 2.12701809e+03,  1.00287669e+02, -1.83193608e+01,
         1.20993325e+01],
       [-5.20808520e+02,  2.30213514e+00, -1.45332516e+00,
         2.67183398e+00],
       [-1.96893522e+02,  2.11030801e+01, -3.42817678e+00,
        -2.16669011e+00],
       [-6.20561204e+02, -4.80937943e+01,  1.03728396e+01,
         3.53706564e+00],
       [-7.45022121e+02, -5.74316913e+01,  1.02208305e+01,
         1.13489051e+01],
       [-1.92430670e+02, -5.30836619e+00, -1.40192112e+01,
        -2.14227657e+00],
       [-3.68577841e+02,  4.34158113e+00, -1.04685131e+01,
         7.63639389e+00],
       [-2.25523469e+02,  6.65180582e+01,  1.67397624e+01,
         5.20685414e+00],
       [-3.92929018e+02, -7.66612386e+00,  5.21041047e-01,
         7.16989720e+00],
       [-4.01674388e+02, -2.81147381e+01,  1.27064939e+01,
        -3.48794642e+00],
       [-4.07535831e+02, -3.31164214e+01, -2.14485653e+00,
        -2.23852568e+00],
       [-1.34103392e+02, -1.22788020e+01, -1.54762837e+01,
         4.40918466e+00],
       [ 9.91378730e+02,  1.54526767e+02,  4.12649892e+00,
         2.91743303e+00],
       [-5.56616798e+02, -2.12657990e+00,  1.10454249e+00,
         1.50323836e+00],
       [ 1.13558195e+03,  7.70746271e+01, -1.60409169e+01,
         5.23381341e+00],
       [-1.43994567e+02,  5.76046787e+01, -1.50710426e+01,
        -9.03927485e+00],
       [-4.65866538e+02, -8.71339267e+00,  6.06691010e+00,
        -8.90498663e+00],
       [-7.90313242e+02, -7.98164915e+01,  2.49104530e+01,
         2.35391682e+00],
       [-8.15980267e+02, -7.43364181e+01,  1.89172431e+01,
         3.06482023e+00],
       [-4.93647933e+02,  3.93097062e+00,  8.49856807e+00,
         5.75523204e+00],
       [-6.07825117e+01,  3.85607131e+01, -1.53775569e+01,
        -1.17303569e+01],
       [-3.96620719e+01,  3.98148220e+01, -1.15500600e+01,
        -7.04200976e+00],
       [-2.76257863e+02,  3.04219303e+01, -7.71146389e+00,
        -9.03490017e+00],
       [-2.01254078e+02,  3.98182400e+01, -6.63489760e+00,
        -2.20796668e+00],
       [-1.71841169e+02,  8.35606068e+00,  2.88523252e-01,
        -3.27099895e+00],
       [-5.97225414e+02, -2.53102998e+01,  7.03969273e+00,
         7.15726707e+00],
       [-6.23076493e+02, -1.45232474e+01,  2.59210256e+00,
         6.16631487e+00],
       [-6.35064042e+02, -4.82346030e+01,  1.45643253e+01,
         3.86458802e+00],
       [-4.73472752e+02, -5.65534073e+01,  1.93838605e+01,
        -6.81734637e+00],
       [-5.54764270e+02, -9.01713146e+00,  1.19874277e+01,
         2.23567920e+00],
       [-5.24660056e+02, -6.28079959e+00,  7.05333616e+00,
        -1.56342166e+00],
       [-3.22054342e+02,  2.23740554e+01, -3.89267608e+00,
        -7.40705882e+00],
       [-7.04967034e+02, -3.13012448e+01,  1.82329325e+01,
         4.64373422e+00],
       [-3.17926338e+02,  2.73694091e+01, -6.16193177e+00,
        -7.47418232e+00],
       [-6.22214536e+02, -1.42743169e+01,  9.33553362e+00,
        -4.48896230e+00],
       [-6.36046256e+02, -1.70436002e+01,  1.29953299e+01,
         5.36689690e+00],
       [-6.70677027e+02, -4.32069594e+01,  2.71822251e+01,
        -4.65145150e+00],
       [-1.25245136e+02,  7.84234325e+01, -1.51592045e+01,
        -6.06786061e+00],
       [-4.79335707e+02, -4.37787349e+00,  3.07657056e+00,
        -8.45028502e+00],
       [-1.77242816e+02,  4.37231432e+01, -1.61152132e+00,
        -9.76831924e+00],
       [-5.18011863e+02, -1.53085472e+00,  1.15923237e+01,
        -7.64625205e+00],
       [ 6.19407986e+01,  3.52648022e+01, -2.40648970e+01,
        -2.59666688e+01],
       [ 1.16713698e+03,  1.05596679e+02,  1.11020736e+01,
        -1.42035033e+01],
       [ 1.41412668e+03,  1.10222492e+02,  4.00659435e+01,
         6.56224017e+00],
       [ 1.04501885e+03,  7.70575885e+01,  3.66688864e-02,
        -4.75324515e+00],
       [ 3.14501756e+02,  4.75535252e+01, -1.04424072e+01,
        -9.77188104e+00],
       [ 1.12485812e+03,  3.41292250e+01, -1.97420874e+01,
        -2.36608814e+01],
       [-7.71527622e+02, -8.86431064e+01,  2.38890319e+01,
         2.54724855e+00]])


labels = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

from sklearn import linear_model
reg = linear_model.LogisticRegression()
reg.fit(data,labels)

new_data = np.array([
  [  0.3,  0.5, -1.2,  1.4],
  [ -1.3,  1.8, -0.6, -8.2]])
print('Predition classes:', reg.predict(new_data))

Predition classes: [1 0]


In [20]:
print('Data shape: ',data.shape,'\n')
print('Labels: ', repr(labels), '\n')

from sklearn import linear_model
reg = linear_model.LogisticRegression(solver= 'lbfgs', multi_class='multinomial')
reg.fit(data, labels)

print('Prediction classes: ',reg.predict(new_data))


Data shape:  (569, 4) 

Labels:  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1,

In [0]:
from sklearn import linear_model
reg= linear_model.LogisticRegression(solver='lbfgs', max_iter=1000)
##default value for max_ter is 100 and for solver-- 'liblinear'


from sklearn import linear_model
reg = linear_model.LogisticRegressionCV(
  solver='multinomial', max_iter=1000)

## **Decision Trees**

The decision tree is a binary tree where each node of the tree decides on a particular feature of the dataset, and we descend to the node's left or right child depending on the feature's value.

https://www.youtube.com/watch?v=5aIFgrrTqOw --**GINI IMPURITY**

In [23]:
from sklearn import tree
clf_tree1 = tree.DecisionTreeClassifier()
reg_tree1 = tree.DecisionTreeRegressor()
clf_tree2 = tree.DecisionTreeClassifier(max_depth=8)
reg_tree2 = tree.DecisionTreeRegressor(max_depth=5)

clf_tree1.fit(data, labels)
clf_tree2.fit(data,labels)
print('Prediction: ',clf_tree1.predict(new_data))
print('Prediction: ',clf_tree2.predict(new_data))

Prediction:  [1 1]
Prediction:  [1 1]


The **max_depth** keyword argument lets us manually set the maximum number of layers allowed in the decision tree. Since large decision trees are prone to overfit data, it can be beneficial to manually set a maximum depth for the tree.

Since scikit-learn uses the CART algorithm, we use **Gini Impurity**, **MSE** (mean squared error), and **MAE** (mean absolute error) to decide on the best feature at each node.

Specifically, for classification trees we choose the feature at each node that minimizes the remaining dataset observations' Gini Impurity. For regression trees we choose the feature at each node that minimizes the remaining dataset observations' MSE or MAE

In [24]:
data = np.array([
  [10.2 ,  0.5 ],
  [ 8.7 ,  0.9 ],
  [ 9.3 ,  0.8 ],
  [10.1 ,  0.4 ],
  [ 9.5 ,  0.77],
  [ 9.1 ,  0.68],
  [ 7.7 ,  0.9 ],
  [ 8.3 ,  0.8 ]])
labels = np.array(
  [1.4, 1.2, 1.6, 1.5, 1.6, 1.3, 1.1, 1.2])

from sklearn.model_selection import train_test_split
split_dataset = train_test_split(data, labels)
train_data = split_dataset[0]
test_data = split_dataset[1]
train_labels = split_dataset[2]
test_labels = split_dataset[3]

print('{}\n'.format(repr(train_data)))
print('{}\n'.format(repr(train_labels)))
print('{}\n'.format(repr(test_data)))
print('{}\n'.format(repr(test_labels)))

array([[ 8.7 ,  0.9 ],
       [ 9.1 ,  0.68],
       [ 8.3 ,  0.8 ],
       [ 9.3 ,  0.8 ],
       [ 7.7 ,  0.9 ],
       [10.2 ,  0.5 ]])

array([1.2, 1.3, 1.2, 1.6, 1.1, 1.4])

array([[ 9.5 ,  0.77],
       [10.1 ,  0.4 ]])

array([1.6, 1.5])



In [26]:
data = np.array([
  [10.2 ,  0.5 ],
  [ 8.7 ,  0.9 ],
  [ 9.3 ,  0.8 ],
  [10.1 ,  0.4 ],
  [ 9.5 ,  0.77],
  [ 9.1 ,  0.68],
  [ 7.7 ,  0.9 ],
  [ 8.3 ,  0.8 ]])
labels = np.array(
  [1.4, 1.2, 1.6, 1.5, 1.6, 1.3, 1.1, 1.2])

from sklearn.model_selection import train_test_split
split_dataset = train_test_split(data, labels,
                                test_size=0.375) 
#default value for test_size is 0.25
train_data = split_dataset[0]
test_data = split_dataset[1]
train_labels = split_dataset[2]
test_labels = split_dataset[3]

print('{}\n'.format(repr(train_data)))
print('{}\n'.format(repr(train_labels)))
print('{}\n'.format(repr(test_data)))
print('{}\n'.format(repr(test_labels)))

array([[10.1 ,  0.4 ],
       [ 9.1 ,  0.68],
       [ 9.5 ,  0.77],
       [ 9.3 ,  0.8 ],
       [ 8.3 ,  0.8 ]])

array([1.5, 1.3, 1.6, 1.6, 1.2])

array([[ 8.7,  0.9],
       [10.2,  0.5],
       [ 7.7,  0.9]])

array([1.2, 1.4, 1.1])



## **Cross Validation**

Using K-Fold algorithm, the model is trained on that round's training set (the combined training folds) and then evaluated on the single validation fold. The evaluation metric depends on the model. 

For classification models, this is usually classification accuracy on the validation set. For regression models, this can either be the model's mean squared error, mean absolute error, or R2 value on the validation set.

In [34]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_breast_cancer
clf = linear_model.LogisticRegression()

cv_score = cross_val_score(clf,data,labels, cv=3)
print(cv_score,'\n')

cv_score = cross_val_score(clf,data,labels, cv=4)
print(cv_score)

[0.93157895 0.96842105 0.93121693] 

[0.92307692 0.96478873 0.96478873 0.92957746]


For classification models, the cross_val_score function will apply a special form of the K-Fold algorithm called **stratified K-Fold**. This just means that each fold will contain approximately the same class distribution as the original dataset. For example, if the original dataset contained 60% class 0 data observations and 40% class 1, each fold of the stratified K-Fold algorithm will have about the same 60-40 split between class 0 and class 1 data observations.

While cross-validation gives us a better measurement of the model's fit on the original dataset, it can be very time-consuming when used on large datasets. For large enough datasets, it is better to just split it into training, validation, and testing sets, and then use the validation set for evaluating the model before it is finalized.

In [40]:
##CROSS VALIDATION FOR DECISION TREE

from sklearn.model_selection import cross_val_score

for depth in range(3, 8):
  # Predefined data and labels
  clf_tree= tree.DecisionTreeClassifier(max_depth=depth)
  scores = cross_val_score(
    clf_tree, data, labels,cv=5)  # k = 5
  mean = scores.mean()  # Mean acc across folds
  std_2 = 2 * scores.std()  # 2 std devs
  print('95% C.I. for depth {}: {} +/- {:.2f}\n'.format(
    depth, mean, std_2))

95% C.I. for depth 3: 0.9120943952802361 +/- 0.04

95% C.I. for depth 4: 0.9332401800962584 +/- 0.03

95% C.I. for depth 5: 0.9297314081664337 +/- 0.03

95% C.I. for depth 6: 0.9174196553330228 +/- 0.02

95% C.I. for depth 7: 0.9192206179164725 +/- 0.04



# **Evaluating Model**

In [52]:
train_data = np.array([[2100,  800],
       [2500,  850],
       [1800,  760],
       [2000,  800],
       [2300,  810]])

train_labels = np.array([10.99, 12.5,9.99, 10.99, 11.99])

test_data = np.array([[2000, 820], [2200,830]])
test_labels = np.array([10.86597417, 11.5511002 ])

reg= tree.DecisionTreeRegressor()
reg.fit(train_data_trans, train_labels)
predictions =  reg.predict(test_data_trans)

from sklearn.preprocessing import Normalizer
norm= Normalizer()
train_data_trans= norm.fit_transform(train_data)
test_data_trans = norm.fit_transform(test_data)

print('Transformed data: ',transformed,'\n')
from sklearn import metrics
r2 = metrics.r2_score(test_labels, predictions)
print('R2:',r2, '\n' )
mse = metrics.mean_squared_error(
  test_labels, predictions)
print('MSE: {}\n'.format(mse))
mae = metrics.mean_absolute_error(
  test_labels, predictions)
print('MAE: {}\n'.format(mae))

clf = tree.DecisionTreeClassifier()
X_train, X_test, Y_train, Y_test = train_test_split(data,labels)

clf.fit(X_train, Y_train)
predictions= clf.predict(X_test)

acc= metrics.accuracy_score(Y_test, predictions)
print(acc)

Transformed data:  [[1. 2. 1. 2.]
 [5. 1. 1. 2.]
 [4. 1. 3. 1.]
 [5. 6. 8. 1.]
 [1. 7. 1. 0.]] 

R2: -0.40697688607774296 

MSE: 0.1651079204736147

MAE: 0.3425630150000005

0.9090909090909091


## **Exhaustive Tuning**

If our application requires us to absolutely obtain the best hyperparameters of a model, and if the dataset is small enough, we can apply an exhaustive grid search for tuning hyperparameters. For the grid search cross-validation, we specify possible values for each hyperparameter, and then the search will go through each possible combination of the hyperparameters and return the model with the best combination.

In [56]:
reg = linear_model.BayesianRidge()
params = {
  'alpha_1':[0.1,0.2,0.3],
  'alpha_2':[0.1,0.2,0.3]
}

from sklearn.model_selection import GridSearchCV
reg_cv = GridSearchCV(reg, params, cv=5)
reg_cv.fit(X_train, Y_train)
print(reg_cv.best_params_)

{'alpha_1': 0.3, 'alpha_2': 0.1}
